### ISSUE TITLE
flow control

### ISSUE THREAD

**Issue by romankh** [ptrkrysik/gr-gsm#100]
As discussed in the mailing list (see https://groups.google.com/forum/#!topic/gr-gsm/LLjv9GKjsf8), we will add some blocks for controlling the burst flow (and later message flow):

* New GRC category "Flow control"
* Add block "Timeslot splitter"
* Add block "Sub-slot splitter" with configuration for SDCCH/4 and SDCCH/8
* Add block "Framenumber filter" with configuration for "less or equal", "greater or equal"
* Add block "Dummy burst filter"

**Comment by romankh** [comment]
I will add two more blocks, as I found that timeslot splitter and sub-slot splitter have a drawback in some use cases. For example, I want to create a flow graph of capable extracting a given SDCCH subslot, where I can set params timeslot, sub-slot and SDCCH config. For that two filter blocks for timeslot and sub-slot with one port in and one port out would be more efficient:

**Comment by ptrkrysik** [comment]
As I'm working currently on uplink support I will add later a filter block that passes downlink and uplink bursts based on user selection.

**Comment by ptrkrysik** [comment]
I'm closing the issue as @romankh created the blocks and the tests of these blocks.
