### ISSUE TITLE
Packaging gr-gsm

### ISSUE THREAD

**Issue by ptrkrysik** [ptrkrysik/gr-gsm#104]
Hi all,

We are looking for someone who has experience in creating deb and rpm packages (or someone who wants to learn how to do this) who would like to modify gr-gsm's cmake based buildsystem in order to create packages for Debian/Ubuntu and Fedora.

**Comment by ashmastaflash** [comment]
I'm open to helping out with this.  What are your contribution guidelines?

**Comment by ashmastaflash** [comment]
What's more important to you, Debian, Ubuntu, or Fedora?

**Comment by ptrkrysik** [comment]
Hi Ash, I've replied on the gr-gsm's mailing-list.

**Comment by DanielMasonNZ** [comment]
A Debian package would be great :+1:

**Comment by bdheeman** [comment]
I usually package each and every project/software before I install and, or test it on/for ArchLinux/ArchLinux-ARM Linux.

Please provide guide lines where in this should we/I add the ArchLinux packaging, I would love to share the PKGBUILD script for gr-gsm :-)

**Comment by ptrkrysik** [comment]
W dniu 25.03.2017 o 19:09, Balwinder S Dheeman pisze:
> I usually package each and every project/software before I install and,
> or test it on/for ArchLinux/ArchLinux-ARM Linux.
> 
> Please provide guide lines where in this should we/I add the ArchLinux
> packaging, I would love to share the PKGBUILD script for gr-gsm :-)
> 
What information do you need to prepare the script?

Currently I know something about Debian packaging (probably I forgot a
lot after few months of not looking into this topic), but I don't know
what is needed for ArchLinux.

**Comment by petterreinholdtsen** [comment]
I'm working on packaging gr-gsm for Debian under the debian-hams umbrella.  You can track the status on https://bugs.debian.org/871055 .

**Comment by petterreinholdtsen** [comment]
The gr-gsm package entered Debian today, see https://tracker.debian.org/pkg/gr-gsm for its status.  Time to close this issue?
