### ISSUE TITLE
Regression in full rate decoding support

### ISSUE THREAD

**Issue by ptrkrysik** [ptrkrysik/gr-gsm#106]
The format of the file produced by the TCH/F decoder for transmission where full rate codec is used is not valid.

$ toast -d speech.au.gsm 
returns
toast: bad frame in speech.au.gsm

**Comment by romankh** [comment]
Will try to find the difference the next days.

**Comment by ptrkrysik** [comment]
As we found out on the list - it's not exactly regression. The block is improved as the file produced by it doesn't need toast conversion now. There is some unpleasant noise at the beginning however. Getting rid of it will require some work.
