### ISSUE TITLE
Error while starting airprobe_rtldsr.py

### ISSUE THREAD

**Issue by KALRONG** [ptrkrysik/gr-gsm#11]
Hi,

I have followed your instructions from a base system working with the old airprobe and while trying to use gr-gsm the error Im pasting below started to appear, I have done a clean install and install using pybombs of the packages you specify but the error still appear. Any idea of whats going on? rtl_sdr seems to be working fine.

Traceback (most recent call last):
  File "/usr/local/bin/airprobe_rtlsdr.py", line 20, in <module>
    import osmosdr
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/**init**.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 28, in <module>
    _osmosdr_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_osmosdr_swig', fp, pathname, description)
ImportError: /usr/local/lib/libgnuradio-osmosdr-0.1.5git.so.0.0.0: undefined symbol: _ZN3uhd6device4findERKNS_13device_addr_tENS0_15device_filter_tE

**Comment by u581** [comment]
Hello my hackrf not working with gr-gsm. No gsm data only Using HackRF One with firmware 2014.08.1 
Using Volk machine: avx_64_mmx_orc
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
Rtl sdr dongle work fine.
help me please with hackrf.
thx

**Comment by ptrkrysik** [comment]
These 'OOOO' means that there is probably some problem with
communication with HackRF. Overflows usually happen when computer can't
consume samples from a receiver. It's strange however that rtl-sdr
works. Can you check that your HackRF works with some example? You can
for example open airprobe_rtlsdr.grc in gnuradio-companion and remove
everything beside fft gui sink and osmosdr source (in case you don't
know how to do this I can provide a grc file). Then report if it works
or not.

**Comment by u581** [comment]
Thanks for the reply. Yesterday I reinstalled ubuntu 14.10 and all work fine.But i dont understend why rtl decodes all channels, hack only some hack
Thx

**Comment by ptrkrysik** [comment]
If you send me GSM signal recorded with HackRF, I can look into it to
find the cause of the problem.

**Comment by u581** [comment]
Can you help me and explain how to do this?

**Comment by ptrkrysik** [comment]
First you need to locate some GSM C0 frequency. You can do this with use
of airprobe_rtlsdr.py and your RTL SDR device. The frequency for which
you see content of messages printed on the output is a good one. Write
it down.

Then download the file  and save it as receive_to_file.grc:
https://app.box.com/s/j93b56tgply596af0qbbii2octds2lka
Open it in gnuradio companion. Set value for parameter fc (double click)
from 939.3e6 to the value that you've written down. Run the flowgraph
with F6.

Send the recording (test_file.cfile) to me using some file transfering
site (for example box.com
<https://app.box.com/s/j93b56tgply596af0qbbii2octds2lka>)

**Comment by u581** [comment]
I'm so sorry, if gain-my bug, all wark fine
