### ISSUE TITLE
commit 242522fbee59c9703d9fed35923486db5effb7d1 breaks first install

### ISSUE THREAD

**Issue by iZsh** [ptrkrysik/gr-gsm#110]
your recent commit 242522fbee59c9703d9fed35923486db5effb7d1 is breaking a first install insofar as it's trying to generate the airprobe_*.py files from grc but of course the module are not yet available in grc's path if it's a first install.

I'm guessing you didn't notice it since you already have gr-gsm installed on your computer

**Comment by ptrkrysik** [comment]
Thanks for the report. I will revert this change until I figure it out
how to do this correctly.
