### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by ijarraki** [ptrkrysik/gr-gsm#113]
I am finding gr-gsm to be spectacularly superior compared to legacy airprobe as far as tuning into and decoding GSM channels. Unfortunately it is *currently* lacking some of said legacy softwares functionality, the highlights of which are:

1: Frame numbers are not shown in console output
2: airprobe_file.py has not options for specifying decimation rate, timeslot, configuration etc
3: airprobe_file.py seems incompatible with capture files made with rtl-sdr and hackrf_transfer and then run through http://pastebin.com/ufbPwRjU (hackrf_transfer)/http://pastebin.com/xrSN3aRn (rtl_sdr). Both these GRCs produce working cfiles to use with airprobe on GnuRadio 3.6

**Comment by romankh** [comment]
Hi, 

please use the mailing list https://groups.google.com/forum/#!forum/gr-gsm for general questions and discussions. 

I answer your question here, if you have more, please use the mailing list.

ad 1: The burst printer has the capability of showing prepending the framenumber for bursts. Maybe we should add this capability to the message printer as well.

ad 2: Decimation can be set by setting the sample rate, for example 100e6/174 where 174 is the decimation rate. Regarding timeslot and configuration: you are right. However there are efforts to create some applications that provide these functionalities directly in the near future. For now you have the option to generate a customized flow graph in grc.

ad 3: I used other captures that were recorded using the old airprobe tool set, and it worked fine. However one has to find the right settings, specially regarding sample rate / decimation. Probably its the same here
