### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by nebukadnezar** [ptrkrysik/gr-gsm#134]
Getting this on trying to compile. Ubuntu 14.04, gcc 4.8.4:

Installing from source: uhd
Building:    (100%) [========================================================================] 
Build failed. Re-trying with reduced makewidth and higher verbosity.
[  4%] [  5%] Built target man_page_gzips
Built target getopt
[  6%] [  6%] [  6%] [  6%] Building CXX object lib/CMakeFiles/uhd.dir/transport/tcp_zero_copy.cpp.o
Building CXX object lib/CMakeFiles/uhd.dir/transport/libusb1_zero_copy.cpp.o
Building CXX object lib/CMakeFiles/uhd.dir/transport/buffer_pool.cpp.o
Building CXX object lib/CMakeFiles/uhd.dir/transport/if_addrs.cpp.o
[  6%] Building CXX object lib/CMakeFiles/uhd.dir/transport/udp_simple.cpp.o
[  7%] Building CXX object lib/CMakeFiles/uhd.dir/transport/chdr.cpp.o
[  7%] Building CXX object lib/CMakeFiles/uhd.dir/transport/nirio_zero_copy.cpp.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [lib/CMakeFiles/uhd.dir/transport/libusb1_zero_copy.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/CMakeFiles/uhd.dir/all] Error 2
make: *** [all] Error 2
Build failed. See output above for error messages.

**Comment by ptrkrysik** [comment]
This is problem with installation of UHD. If you don't use Ettus USRPs you can try to disable installation of uhd by editing pybombs/config.dat.
Edit the line:
forcepkgs = gnuradio,uhd,gr-air-modes,gr-osmosdr,gr-iqbal,gr-fcdproplus,uhd,rtl-sdr,osmo-sdr,hackrf,gqrx,bladeRF,airspy

by removing uhd to:
forcepkgs = gnuradio,gr-air-modes,gr-osmosdr,gr-iqbal,gr-fcdproplus,uhd,rtl-sdr,osmo-sdr,hackrf,gqrx,bladeRF,airspy

Also currently we use git for submitting bugs/possible bugs in gr-gsm. For reporting problems with installation please use the project's mailing list:
https://github.com/ptrkrysik/gr-gsm#mailing-list
I'm closing the issue - we can continue the thread on the mailing list.
