### ISSUE TITLE
No supported devices found to pick from

### ISSUE THREAD

**Issue by d3crypt** [ptrkrysik/gr-gsm#136]
root@kali:~/gr-gsm/apps# airprobe_rtlsdr.py 
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown
I have installed gr-gsm manually and it still isn't working. I can verify its not my Rtlsdr because it works fine in gqrx. 

Here is the output when I try to run it:
root@kali:~/gr-gsm/apps# airprobe_rtlsdr.py 
linux; GNU C++ version 4.9.1; Boost_105500; UHD_003.007.003-0-unknown

gr-osmosdr v0.1.4-67-gac15e789 (0.1.5git) gnuradio 3.7.5
built-in source types: file fcd rtl_tcp uhd rfspace redpitaya 

FATAL: No supported devices found to pick from.

Trying to fill up 1 missing channel(s) with null source(s).
This is being done to prevent the application from crashing
due to gnuradio bug #528.

Using Volk machine: ssse3_64_orc

**Comment by ptrkrysik** [comment]
Can you connect in gnuradio-companion RTL-SDR source to null sink and
check if it works?

**Comment by d3crypt** [comment]
I will do so and post back.

**Comment by d3crypt** [comment]
I fixed it. It was a problem with how i build gr-osmosdr.

**Comment by drsn0w** [comment]
How did you fix this?

**Comment by Dr4s1l** [comment]
How did you fix this?

**Comment by velichkov** [comment]
Hi @Dr4s1l, @drsn0w,

Check that the gr-osmosdr is compiled with RTL support. When compiling from source you could specify `-DENABLE_RTL=ON` cmake option and if you see the following error

```
$cmake -DENABLE_RTL=ON ..

-- Configuring Osmocom RTLSDR support...
--   Dependency LIBRTLSDR_FOUND = FALSE
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GrComponent.cmake:75 (message):
  user force-enabled Osmocom RTLSDR but configuration checked failed
Call Stack (most recent call first):
  lib/CMakeLists.txt:156 (GR_REGISTER_COMPONENT)
```
then you need to install the librtlsdr library and header files. On ubuntu 16.04 you could install it from the repository
```
sudo apt-get install librtlsdr-dev
```

**Comment by Dr4s1l** [comment]
Workshop for me. On fedora using pybombs, install allô package, do
```
pybombs inv rtl-sdr
Pybombs remove rtl-sdr
pybombs install rtl-sdr
```
Workshop better with sudo for me

**Comment by Rajatdongre** [comment]
if i am using hackrf what should I do ? for osmocomm. i also getting same error
