### ISSUE TITLE
ImportError: cannot import name Range

### ISSUE THREAD

**Issue by ijarraki** [ptrkrysik/gr-gsm#137]
Ref issue #125 

This still happens with the latest gr-gsm on Debian Jessie and Kali (sana/2.0).

**Comment by ijarraki** [comment]
I resolved this issue by compiling/installing latest/git gnuradio, libosmocore, rtl-sdr and gr-osmosdr before compiling/installing gr-gsm.

**Comment by jarodcs** [comment]
Hi, just want to share that I had this error:

xxxxxxx@debian:~/Documents/gr-gsm$ grgsm_livemon 
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 32, in <module>
    import osmosdr
ImportError: No module named osmosdr          <<<<<<<<<<<<<<<<<< ERROR! <<<<<<<<

I and pass this through once  running
sudo apt-get install gr-osmosdr 
(No need to compile/install again, but just in case)

Cheers
