### ISSUE TITLE
Missing functionality/wrong output in airprobe_decode

### ISSUE THREAD

**Issue by ijarraki** [ptrkrysik/gr-gsm#138]
Looking at https://github.com/ptrkrysik/gr-gsm/wiki/Usage:-Decoding-How-To and taking vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile as an example, airprobe_decode allows us to extract voice data by supplying certain parameters, including the Kc. In this example the Kc is already known (filename) and in certain other cases be determined by phone-specific service menu, cold extraction from the SIM, etc.

What the current gr-gsm and airprobe_decode do not contribute to is research into attemptive, opportunistic determination of the Kc in cases where a phone does not provide a "service menu" or a cold extraction of the relevant Kc is not feasible. Again taking vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile as an example, we know there is a "System Information Type 5"/"SIT5" message in frames 862242/862245 as well as an "ESIT5" message some frames later. This data is not output by airprobe_decode in any useful way which is seemingly acknowledged at https://groups.google.com/forum/?_escaped_fragment_=topic/gr-gsm/odPheUrcbAw#!topic/gr-gsm/odPheUrcbAw

We would need airprobe_decode to  at least have an option/parameter to provide output comparable to that of legacy airprobe?

**Comment by ptrkrysik** [comment]
No, currently I don't plan to add to gr-gsm project options/functionalities making it compatible with Kraken. I would be much more excited to see gr-gsm be used for something ethical (like IMSI catchers detection) and not snooping on others. 

I might create some application that will have output compatible with Kraken (it is really not hard if you know what you are doing) but it will be separate from gr-gsm.
