### ISSUE TITLE
Cannot write to prefix path `/usr/local'

### ISSUE THREAD

**Issue by MatejKovacic** [ptrkrysik/gr-gsm#146]
I am following instructions from wiki and after I write:
pybombs prefix init /usr/local -a default_prx

I got an error:
PyBombs.prefix - ERROR - Cannot write to prefix path `/usr/local'.

**Comment by ptrkrysik** [comment]
I think that adding sudo solved this issue. In case it didn't I will reopen the issue.

**Comment by jacobitosuperstar** [comment]
hi, im here to comment that it didn't work

**Comment by velichkov** [comment]
Hi @jacobitosuperstar,

What do you get when you execute it? Please provide the full command that you have executed including all arguments together with the whole output. And also which OS do you use and which version?

In my opinion the `pybombs` installation method is the hardest one and most error prone so my advice is to fist try some of the other installations methods described [here](https://osmocom.org/projects/gr-gsm/wiki/Installation).

**Comment by jacobitosuperstar** [comment]
Yeah I just switched the installation and that’s it, sorry for the inconvenience... But in case it helps I use MacOS Mojave and i get the same error that guy above even after I use Sudo I get the same promp, “cannot write prefix path”

**Comment by velichkov** [comment]
> I use MacOS Mojave

The MacOS is not well supported platform, I recommend you to first try installing and using gr-gsm on Linux, even in a VM.

> i get the same error that guy above even after I use Sudo I get the same promp, “cannot write prefix path”

I don't have any MacOS experience but maybe [this](https://support.apple.com/en-us/HT204012) and [this](
https://superuser.com/questions/1021141/problems-with-sudo-privileges-as-admin-in-osx) could help you resolve the `sudo` problem.
