### ISSUE TITLE
Fix frequency<->arfcn conversion

### ISSUE THREAD

**Issue by ptrkrysik** [ptrkrysik/gr-gsm#154]
frequency<->arfcn doesn't always work in the way consistent with the standard.
grgsm.arfcn.downlink2arfcn(freq, 'E-GSM') doesn't work in freq. range 930e6 to 959.8e6 (which is part of the E-GSM band).

**Comment by romankh** [comment]
Will fix that

**Comment by romankh** [comment]
Hi @ptrkrysik,
I think the issue is fixed and can be closed, can you verify ?

**Comment by ptrkrysik** [comment]
Thanks @romankh for pointing this.
