### ISSUE TITLE
obtaining .grc files

### ISSUE THREAD

**Issue by falcorocks** [ptrkrysik/gr-gsm#156]
Ok so i finally installed everything and got my dongle working.
After going in gr-gsm/apps/ i can run grgsm_livemon.grc and it seems to work.
I do:
gnuradio-companion grgsm_livescanner.grc

What I really need though is to use the other apps!
But gnuradio-companion grgsm_scanner gives an error!
I noticed that there are three files for grgsm_livescanner: one ending in .py, one ending in .grc (the one I launch) and one ending with no extension.
For grgsm_scanner and grgsm_decode though only the files ending with no extensions are present...
Now I'm a complete gnuradio n00b but I get that I need somehow to get the .grc from these last two files. How? Are they just missing or what?

**Comment by ptrkrysik** [comment]
W dniu 25.02.2016 o 21:07, falcorocks pisze:
> Ok so i finally installed everything and got my dongle working.
> After going in gr-gsm/apps/ i can run grgsm_livemon.grc and it seems to
> work.
> I do:
> gnuradio-companion grgsm_livescanner.grc
> 
> What I really need though is to use the other apps!
> But gnuradio-companion grgsm_scanner gives an error!
> I noticed that there are three files for grgsm_livescanner: one ending
> in .py, one ending in .grc (the one I launch) and one ending with no
> extension.
> For grgsm_scanner and grgsm_decode though only the files ending with no
> extensions are present...
> Now I'm a complete gnuradio n00b but I get that I need somehow to get
> the .grc from these last two files. How? Are they just missing or what?
> 

grgsm_livemon application was prepared using gnuradio-companion and
grgsm_livemon.grc file. Other applications were written manually in
python. You shouldn't use gnuradio-companion to run them. Just invoke
the commands directly:
-grgsm_scanner,
-grgsm_livemon,
-grgsm_decode.

-- 
Best Regards,
Piotr Krysik
