### ISSUE TITLE
GSM capture error

### ISSUE THREAD

**Issue by Pradyumna007** [ptrkrysik/gr-gsm#159]
I am using Ubuntu Live CD of GNU Radio .... GNUradio version is 3.7.8. I am trying to use gr-gsm. The airprobe_rtlsdr.grc is getting executed but the point is there are no 2b packets getting captured. Any solution ?

**Comment by ptrkrysik** [comment]
I think it might be the #148 issue. I'm closing it here but I will reopen it if you show some data presenting that it is something different.
