### ISSUE TITLE
more timeslots?

### ISSUE THREAD

**Issue by KALRONG** [ptrkrysik/gr-gsm#16]
Hi,

Im trying to analyze traffic from my mobile but I see that gr-gsm doesn't have the option like airprobe to analyze other timesloys than 0. Can this feature be included?

I have tried to run the old airprobe for this while I have gr-gsm fully functional but is complaining about the gsm library saying that module doesnt have the attirbute receiver_cf.

Im stil understanding the code so I can try to make some contributions to this project but Im still really new to this so Im just trying to test it as much as I can and provide the feedback I can.

Thanks in advance.

**Comment by ptrkrysik** [comment]
Hi @KALRONG you can receive timeslots other than 0 with the receiver block (there is even not documented yet option to receive other ARFCNs than C0). To see this you can connect bursts_printer directly to the receiver's output. However there are no blocks to decode traffic channels yet.
