### ISSUE TITLE
grgsm_scanner error

### ISSUE THREAD

**Issue by falcorocks** [ptrkrysik/gr-gsm#166]
Suddendly grgsm_scanner stopped working.
Everything else works so it's not the dongle...
This is what I'm getting

`linux; GNU C++ version 5.2.1 20151010; Boost_105800; UHD_003.010.git-0-2d68f228

Traceback (most recent call last):
  File "/usr/local/bin/grgsm_scanner", line 393, in <module>
    for info in sorted(found_list):
  File "/usr/local/bin/grgsm_scanner", line 293, in **cmp**
    return self.getKey().**cmp**(other.getKey())
AttributeError: 'NoneType' object has no attribute '**cmp**'
Reattached kernel driver`

otherwise i'm also getting this

`linux; GNU C++ version 5.2.1 20151010; Boost_105800; UHD_003.010.git-0-2d68f228

Traceback (most recent call last):
  File "/usr/local/bin/grgsm_scanner", line 394, in <module>
    print info
  File "/usr/local/bin/grgsm_scanner", line 296, in **repr**
    return "ARFCN: %4u, Freq: %6.1fM, CID: %5u, LAC: %5u, MCC: %3u, MNC: %3u, Pwr: %3i" % (self.arfcn, self.freq/1e6, self.cid, self.lac, self.mcc, self.mnc, self.power)
TypeError: %u format: a number is required, not NoneType
Reattached kernel driver

`

**Comment by ptrkrysik** [comment]
It seems like some bug in the scanner. One of the parameters had value None. Probably ARFCN.
I'm marking it as bug.

**Comment by romankh** [comment]
@falcorocks: does this bug still exist with current master ? think it may have been fixed by the changes on arfcn calculation in commit 385a606119ce43fd575c604717463f1453625c46

**Comment by petterreinholdtsen** [comment]
The problem still exist in master.  It has been fixed in the packaging branch with commit aed9f5cc80e2c123eb0294dff21e853c1ffa376b .

**Comment by petterreinholdtsen** [comment]
A fix for this is now included in master and was part of the 0.41.1 release.  Time to close this issue as fixed?
