### ISSUE TITLE
airprobe_file.py not sending any data

### ISSUE THREAD

**Issue by KALRONG** [ptrkrysik/gr-gsm#17]
Hi,

I have tried to use airprobe_file.py with the usual example for the old go.sh and with a couple of test captures I did but nothing appears on wireshark listenning on lo, maybe im missing something?

This is the command Im running:

airprobe_file.py --samp-rate=1M --fc=941.8M -i ~/airprobe-old/gsm-receiver/src/python/capture_941.8M_112.cfile 

CPU spikes for a little time and then it just stops doing nothing.

Thanks in advance.

**Comment by ptrkrysik** [comment]
@edorexy I've corrected the error pointed by you. Sample rate is probably different for the file that you've sent. Probably it should be something near to 64.0e6/112. If you send me the file I can test it myself.

**Comment by edorexy** [comment]
This is the normal gsm capture  cfile available on the internet 

Regards,

**Comment by ptrkrysik** [comment]
I can open the file with following command:
./airprobe_file.py -s 571428.57142857 -i /home/piotr/Pobrane/capture_941.8M_112.cfile.part

**Comment by edorexy** [comment]
capture_941.8M_112.cfile  Downloads         Public                Templates
capture.bin               examples.desktop  pybombs               Videos
Desktop                   Music             qthid-4.1-linux-i386
Documents                 Pictures          README.txt
rex@ubuntu:~$ ./airprobe_file.py -s 571428.57142857 -i capture_941.8M_112.cfilebash: ./airprobe_file.py: No such file or directory
rex@ubuntu:~$ ./airprobe_file.py -s 571428.57142857 -i capture_941.8M_112.cfil

**Comment by ptrkrysik** [comment]
You are openning from a directory that doesn't have airprobe_file.py file.
To make sure everything works go into gr-gsm source directory (probably pybombs/src/gr-gsm) and do:
```
git pull
cd build; make; make install
airprobe_file.py -s 571428.57142857 -i path_to_the_capture_file/capture_941.8M_112.cfile
```

**Comment by edorexy** [comment]
done, same results...command not found

**Comment by edorexy** [comment]
![capture_941 8m_112 cfile](https://cloud.githubusercontent.com/assets/5991994/5601150/9549c55c-92ef-11e4-8229-bf3569caaf84.png)

**Comment by ptrkrysik** [comment]
Please execute the flowgraph in gnuradio-companion. You can do this for example by pressing F6. At the bottom of the gnuradio-companion window you will see program output messages. In case of errors you will get error messages in there.

**Comment by edorexy** [comment]
Hi, coming back to my project today. I have started receiving "runtimeerror audio_alsa_source"

what is your recommendation i do, thank you in adavnace

**Comment by ptrkrysik** [comment]
I'm completely puzzled by this - the airprobe_file.py doesn't use alsa
source at all. Do you get any other errors/indications of what might be
wrong?

**Comment by edorexy** [comment]
me too, what do suggest i do now?

**Comment by ptrkrysik** [comment]
I need a way to reproduce your problem. Tell me all the details what
operating system you have (distribution, version). How you installed
gr-gsm. How are you running it airprobe_file.py. Everything.

Try also running airprobe_file.grc in gnuradio companion. Give me all of
the output after running it.

**Comment by edorexy** [comment]
i am using vmware ubuntu 14.04, the run-time error occurs when running airprobe_file.grc in gnuradio companion.

**Comment by ptrkrysik** [comment]
This information doesn't help in any way. I have also Ubuntu 14.04 and
don't get any of such errors. Remove gr-gsm and gnuradio before and try
to install it again using pybombs. If you will want me to help you will
also have to give me much more information. I can't guess what happens
on your system.

**Comment by edorexy** [comment]
i can arrange a team-viewer access to the machine, if you can agree an appropriate date/time that is convenient for you.

**Comment by edorexy** [comment]
Hello, I have had some luck fixing the issue and now needs to pipe data output into file and make a capture file...kindly assist!

**Comment by ptrkrysik** [comment]
Find a frequency for which you are sure that it's gsm broadcasting
channel central frequency. It should be in range from 925e6 to 960e6 Hz.
You can use airprobe_rtlsdr.py for it, as it have simple spectrum plot.
The broadcasting channel should have constant amplitude all the time.

In the attached flowgraph:

Dodatkowy załącznik dla tej wiadomości:
airprobe_rtlsdr.grc
<https://app.box.com/s/1u05pd1pvzy2d2s01pxppk3pxwfeng92>(51,7 KB)Box
<https://www.box.com/thunderbird>https://app.box.com/s/1u05pd1pvzy2d2s01pxppk3pxwfeng92
Program Mozilla Thunderbird <http://www.getthunderbird.com> ułatwia
przesyłanie dużych plików pocztą.
set fc to the frequency value that you've found before and run it. It
will record 5 seconds of raw signal into "recording" file. Send the file
to a filesharing service and post the link here.

**Comment by sterces** [comment]
How did you reverse engineer the proper sample_rate for the ...112.cfile ?

If I record from GQRX and capture from UDP to a file, how do I translate the GQRX info to playback by airprobe_file.py.....or to I need an interim conversion???

Any help appreciated.

Sterces

**Comment by ptrkrysik** [comment]
The 112 value was decimation rate setting for USRP1. The original
sampling rate of that device was 64MHz and after decimation by 112 it gives:
64e6/112 ~= 571428.5714 [Hz]

Regarding the second question - I don't use GQRX and I don't know what
is the format of it's captures so I don't know how it can be done.

However you don't need GQRX to record on a given frequency.
If you have RTL-SDR you can for example use rtl_sdr commandline program.
You can also use gnuradio-companion: configure RTL-SDR source (carrier
frequency and gain), connect it to file sink, then run the flowgraph for
few seconds - and you have a file with raw signal.

**Comment by Srg123r** [comment]
what should be the sample rate and decimation rate if we have to use RTL-SDR for capturing and decoding .cfiles instead of USRP?
