### ISSUE TITLE
Unable to load airprobe_rtlsdr.grc file

### ISSUE THREAD

**Issue by bashar0151** [ptrkrysik/gr-gsm#170]
Every time i try to load this file on GNU radio i get this error:

<<< Welcome to GNU Radio Companion 3.7.2.1 >>>

Loading: "/home/bashar/Desktop/gr-gsm/apps/airprobe_rtlsdr.grc"
Error: Specification mandate value for attribute data-pjax-transient, line 50, column 40
>>> Failure

Showing: ""

any ideas? 

using Ubuntu 14.04LTS

**Comment by ptrkrysik** [comment]
Gnuradio 3.7.2 is not supported. Install 3.7.3 or above.
