### ISSUE TITLE
I can not install gr-gsm 

### ISSUE THREAD

**Issue by Zheka1988** [ptrkrysik/gr-gsm#173]
WARNING : The following packages can not be authenticated !
        libsigsegv2 m4 autoconf autotools-dev automake
There are problems and setting -y set free  --force-yes
Configuring: (100%) [=========================================================]
PyBombs.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether ln -s works... yes
checking for perl... /usr/bin/perl
checking for tex... no
checking for yacc... no
checking for byacc... no
checking for bison... no
checking for lex... no
checking for flex... no
checking whether autoconf is installed... no
configure: error: Autoconf 2.65 or better is required.
    Please make sure it is installed and in your PATH.
PyBombs.Packager.source - ERROR - Configuration failed after running at least twice.
PyBombs.Packager.source - ERROR - Problem occurred while building package automake:
Configuration failed
PyBombs.install - ERROR - Error installing package automake. Aborting.

could you give me advise about my problem.

**Comment by ptrkrysik** [comment]
Ask the question on the mailing list. Read this:
https://github.com/ptrkrysik/gr-gsm#mailing-list
