### ISSUE TITLE
gr-gsm does not exist

### ISSUE THREAD

**Issue by nomorecats** [ptrkrysik/gr-gsm#175]
PyBombs.DepManager - ERROR - Package does not exist: ssl (declared as dependency for package libevent)

**Comment by tiger762** [comment]
In general, what I try is:

yum install (package)                 (on Fedora / RedHat)
apt-get install (package)            (on Debian / Ubuntu / Raspbian)

In your case, I checked my Fedora 21 box and have these packages that look SSL related:

openssl-libs-1.0-1k-12.fc21.x86_64
openssl-1.0-1k-12.fc21.x86_64
openssl-devel-1.0-1k-12.fc21.x86_64

**Comment by ptrkrysik** [comment]
Installation of gr-gsm is generally discussed on the mailing list. This doesn't look like issue with gr-gsm but with your particular environment.
