### ISSUE TITLE
Build instructions for Fedora 23 64-bit

### ISSUE THREAD

**Issue by tiger762** [ptrkrysik/gr-gsm#180]
For educational purposes, I offer my command log of upgrading a machine this evening to Fedora 23 64-bit

Install these packages:

```
dnf update
dnf install gnuradio
dnf install gnuradio-devel
dnf install gr-osmosdr
dnf install libosmocore
dnf install automake
dnf install libtool
dnf group install "Development Tools"
dnf install gcc-c++
dnf install fftw3
dnf install fftw3-devel
dnf install rtl-sdr-devel
dnf install libusb-devel
dnf install cppunit
dnf install cppunit-devel
dnf install libosmocore-devel
dnf install swig
dnf install wireshark
dnf install wireshark-gnome
```

Follow Piotr's manual installation commands:

```
git clone https://github.com/ptrkrysik/gr-gsm
cd gr-gsm
mkdir build
cd build
cmake ..
make
make install
```

open grgsm_livemon.grc to generate grgsm_livemon.py

If you get this weird-ass error:

```
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x1a0000b
```

Then export this environment variable:
`export QT_X11_NO_MITSHM=1`

Now I was able to run grgsm_livemon.py :smile:
`./grgsm_livemon.py -f 893.8e6 -g 49 -p 55`

Hope this helps someone!

**Comment by ptrkrysik** [comment]
This is now described on the new project's wiki: https://osmocom.org/projects/gr-gsm/wiki/Installation
