### ISSUE TITLE
missed module.

### ISSUE THREAD

**Issue by vimcma** [ptrkrysik/gr-gsm#185]
Hello, 

after all installations I've started grgsm_livemon.grc with GNU Radio and after pressing button PLAY I've got the next error >>>

>
Traceback (most recent call last):
  File "/home/root/GNU_RADIO_Projects/grgsm_livemon.py", line 30, in <module>
    import grgsm
ImportError: No module named grgsm
<

Please advice what I've done wrong way?

**Comment by ptrkrysik** [comment]
For support - please go to the mailing-list. 
Don't forget to include more information on:
-how did you install gr-gsm,
-what distribution you use,
etc.
