### ISSUE TITLE
pkg-config problem during the instations

### ISSUE THREAD

**Issue by Matat93** [ptrkrysik/gr-gsm#186]
Hey :)
I'm trying to install gr-gsm ubuntu 14.04 
i follow the instructions and I see this error during installation . I hopes there is  a solution to this problem.

PyBombs.install - INFO - Installation successful.
PyBombs.install - INFO - Installing package: pkg-config
PyBombs.Fetcher - ERROR - Unexpected error while fetching wget+https://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz.
PyBombs.Fetcher - ERROR - hostname 'pkgconfig.freedesktop.org' doesn't match either of 'distributions.freedesktop.org', 'farsight.freedesktop.org', 'fontconfig.freedesktop.org', 'fontconfig.org', 'freedesktop.org', 'geoclue.freedesktop.org', 'secure.freedesktop.org', 'www.fontconfig.org', 'www.freedesktop.org'
PyBombs.Packager.source - ERROR - Problem occurred while building package pkg-config:
Unable to fetch recipe pkg-config
PyBombs.install - ERROR - Error installing package pkg-config. Aborting.

**Comment by ptrkrysik** [comment]
Hi @Matat93 ,
Can we discuss this on the mailing-list? This is most probably support request.
