### ISSUE TITLE
CODEC and TCH HALF RATE

### ISSUE THREAD

**Issue by mamoonali** [ptrkrysik/gr-gsm#188]
hi,
1. how to determine whether a network is using FR,EFR ,AMR?

 2   is it possble to decode tch-half rate channel?

 3   i have a sample in which in can get the calling subscrier number . But unable to decode the voice. plz. suggest me in it.

  4  does gr-gsm works fine for amr codec?

  5  grgsm works fine for open BTS as i have intercepted voice calls in FR mode.

    regards..

**Comment by ptrkrysik** [comment]
I'm closing the issue - we can continue on the mailing list.

**Comment by mamoonali** [comment]
Right sir..issue is closed on page.Looking forward in mailing list
