### ISSUE TITLE
No Data coming from grgsm_livemon

### ISSUE THREAD

**Issue by greg5678** [ptrkrysik/gr-gsm#196]
I installed grgsm on my raspberry pi 3 by following the instructions for the pi 3. I selected channel 234 running at 890.4 mhz. It wouldn't run the the terminal because it gave me an error about there being no module named range so I ran it from gnuradio companion. I selected the 890.4 mhz frequency but I am not getting any data. It says Using volk machine: neon_hardpf_orc but no errors.

**Comment by ptrkrysik** [comment]
I've never run gr-gsm on rasbery pi. If you want to get some ideas/support - please ask on the mailing-list:
https://github.com/ptrkrysik/gr-gsm#mailing-list
