### ISSUE TITLE
TypeError: msg_connect() takes exactly 5 arguments (3 given) (Raspberry Pi 3)

### ISSUE THREAD

**Issue by greg5678** [ptrkrysik/gr-gsm#199]
I have followed the instructions to install gr-gsm on my Raspberry Pi 3. My pi is running gnuradio 3.7.5. It gives me this error TypeError: msg_connect() takes exactly 5 arguments (3 given). My pi is running Raspbian 4.4.13-v7

**Comment by ptrkrysik** [comment]
This is duplicate of #187
