### ISSUE TITLE
Problems execute airprobe_rtlsdr.py 

### ISSUE THREAD

**Issue by EloyBeltran** [ptrkrysik/gr-gsm#200]
Step 6 of this tutorial of instalation gr-gsm http://www.rtl-sdr.com/rtl-sdr-tutorial-analyzing-gsm-with-airprobe-and-wireshark/.

The terminal said: 

root@kali:~# airprobe_rtlsdr.py
Traceback (most recent call last):
  File "/usr/local/bin/airprobe_rtlsdr.py", line 19, in <module>
    from gnuradio import blocks
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/__init__.py", line 32, in <module>
    from blocks_swig import *
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig.py", line 22, in <module>
    from blocks_swig0 import *
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 26, in <module>
    _blocks_swig0 = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 22, in swig_import_helper
    _mod = imp.load_module('_blocks_swig0', fp, pathname, description)
ImportError: libgnuradio-runtime-3.7.10git.so.0.0.0: cannot open shared object file: No such file or directory

----------------------------------------------

Lookin in to libraries and binaries files:

 File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/__init__.py", line 32, in <module>
    from blocks_swig import *

#
# Copyright 2012 Free Software Foundation, Inc.
#
# This file is part of GNU Radio
#
# GNU Radio is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Radio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Radio; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

'''
Processing blocks common to many flowgraphs.
'''
import os

try:
    from blocks_swig import *
except ImportError:
    dirname, filename = os.path.split(os.path.abspath(__file__))
    __path__.append(os.path.join(dirname, "..", "..", "swig"))
    from blocks_swig import *

from stream_to_vector_decimator import *

#alias old add_vXX and multiply_vXX
add_vcc = add_cc
add_vff = add_ff
add_vii = add_ii
add_vss = add_ss
multiply_vcc = multiply_cc
multiply_vff = multiply_ff
multiply_vii = multiply_ii
multiply_vss = multiply_ss

----------------------------------------------------------------

 File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig.py", line 22, in <module>
    from blocks_swig0 import *

#
# Copyright 2013 Free Software Foundation, Inc.
#
# This file is part of GNU Radio
#
# GNU Radio is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Radio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Radio; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street,
# Boston, MA 02110-1301, USA.
#

from blocks_swig0 import *
from blocks_swig1 import *
from blocks_swig2 import *
from blocks_swig3 import *
from blocks_swig4 import *
from blocks_swig5 import *

---------------------------------------------------------------------

Loking in to files :

File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 26, in <module>
    _blocks_swig0 = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig0.py", line 22, in 

# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_blocks_swig0', [dirname(__file__)])
        except ImportError:
            import _blocks_swig0
            return _blocks_swig0
        if fp is not None:
            try:
                _mod = imp.load_module('_blocks_swig0', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _blocks_swig0 = swig_import_helper()
    del swig_import_helper
else:
    import _blocks_swig0
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.

Restart the instalation gr-gsm?

**Comment by ptrkrysik** [comment]
This looks more like support request not a bug. Please make a post on the mailing list.
