### ISSUE TITLE
Request for decoding frequency hopping enabled SDCCH8 and TCH/F

### ISSUE THREAD

**Issue by Varbaek** [ptrkrysik/gr-gsm#215]
Hi Ptrkrysik, 

I was wondering if it would be possible for you to implement a wideband decoder based on bogdan's work?

https://github.com/BogdanDIA/airprobe-hopping

**Comment by ptrkrysik** [comment]
It's possible. The GSM receiver block already supports hopping.
Currently everything works offline with channelization done manually
(through calling grgsm_channelize.py helper script) and configuration of
the hopping entered by the user.
