### ISSUE TITLE
Need help on DSP C66x

### ISSUE THREAD

**Issue by Niran05** [ptrkrysik/gr-gsm#218]
hi,

Am currently working on TI DRA74x Jacinto 6 board. It has ARM core A15 and M4. and 1 DSP C66X.Am running the code only on ARM A15.(.ubuntu 12.04 with kernel 3.13) but processing speed is low..

I want to use DSP C66X for image processing application.i found DSPLIB is a library from TI for DSP.

 Is there another way to cross compile DSPLIB into.Linux..?

DRA74x board only support GLSDK from TI.is there way to cross compile DSPLIB to GLSDK..?

am new to this... plz help me.

**Comment by ptrkrysik** [comment]
Hi @Niran05. This question is wrongly addressed. This is venue to report bugs and proposing improvements in gr-gsm project.
