### ISSUE TITLE
Gr-gsm doesn't work with Fun Cube dongle

### ISSUE THREAD

**Issue by ptrkrysik** [ptrkrysik/gr-gsm#23]
Hi all,

I've reports that gr-gsm doesn't work with Fun Cube dongle. I would greatly appreciate confirmations from other sources and captures of raw GSM signal, sou I could debug the problem.

**Comment by dmaynor** [comment]
There are two models, any details on which?

**Comment by ptrkrysik** [comment]
Oh, it might explain quite well why it doesn't work :). I'm closing the issue then.
