### ISSUE TITLE
grgsm_swigPYTHON_wrap.cxx.o error

### ISSUE THREAD

**Issue by TNSPredator** [ptrkrysik/gr-gsm#236]
Hello

I am trying to install gr-gsm onto a Beaglebone Black which is running Arch Linux arm. Unfortunately I keep receiving the following error upon compiling the source code. I have ensured that I have all of the dependencies installed. I have also tried installing gr-gsm through PyBombs but still no luck. How can I resolve the following error?

`
[ 78%] Building CXX object swig/CMakeFiles/_grgsm_swig.dir/grgsm_swigPYTHON_wrap.cxx.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/archlinuxarm/PKGBUILDs/issues> for instructions.
make[2]: *** [swig/CMakeFiles/_grgsm_swig.dir/build.make:69: swig/CMakeFiles/_grgsm_swig.dir/grgsm_swigPYTHON_wrap.cxx.o] Error 4
make[1]: *** [CMakeFiles/Makefile2:525: swig/CMakeFiles/_grgsm_swig.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
`

Many thanks!

**Comment by ptrkrysik** [comment]
The problem is described here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61860

" Mikael Pettersson 2014-07-20 22:53:49 UTC

You ran out of RAM during the g++ job so the kernel killed it.  You need more RAM (preferably), or to add some swap (unpleasant but sometimes necessary)."
