### ISSUE TITLE
Feature request: decoding TCH/9.6

### ISSUE THREAD

**Issue by bdyaods** [ptrkrysik/gr-gsm#237]
hi, all:
    I want to decode the data in TCH/F9.6, but I can't find any guide, can you give me some advices?
    Thanks a lot

**Comment by ptrkrysik** [comment]
W dniu 23.11.2016 o 09:19, bdyaods pisze:
> hi, all:
> I want to decode the data in TCH/F9.6, but I can't find any guide, can
> you give me some advices?
> Thanks a lot
> 
Currently decoding of data channels is not supported. The support can be
quite easily added as libosmocore has the decoding implementation.

**Comment by axilirator** [comment]
> The support can be quite easily added as libosmocore has the decoding implementation.

It already has ;)

**Comment by E3V3A** [comment]
@ptrkrysik So was this implemented?

**Comment by ptrkrysik** [comment]
The support of encoding/decoding different channel codes was ported by
Vadim to libosmocore. But it will need to be integrated into gr-gsm.
