### ISSUE TITLE
Feature request: add GSM850 to grgsm_livemon.grc

### ISSUE THREAD

**Issue by bmcdanel** [ptrkrysik/gr-gsm#245]
Change qt element "fc_slider->start" to 869.2M to make it easier to do GSM850.

**Comment by belahssen** [comment]
how can i sniffing with GSM tool ican't please say what can i do :+1:

**Comment by aguilasainz** [comment]
bmcdanel, which file should I edit for your suggestion?

**Comment by Nom-DePlume** [comment]
New account, same user.

93ba6bc2c24eef808fafa41233102e59e56ff1d8 fixed it

grgsm_livemon.grc line 128

This may be closed.
