### ISSUE TITLE
segmentation fault while loading grgsm_livemon.grc into gnu radio companion

### ISSUE THREAD

**Issue by thejunaid** [ptrkrysik/gr-gsm#250]
gnuradio-companion grgsm_livemon.grc
<<< Welcome to GNU Radio Companion 3.7.10 >>>

Block paths:
	/root/.grc_gnuradio
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks
Warning: restarting the docstring loader (crashed while loading 'osmosdr_sink')
Warning: restarting the docstring loader (crashed while loading 'osmosdr_source')
Warning: restarting the docstring loader (crashed while loading 'uhd_amsg_source')

**Comment by ptrkrysik** [comment]
This description doesn't tell me much. It is probably some problem with installation of GNU Radio. If you need some help with installation you will need to ask on the mailing list:
https://github.com/ptrkrysik/gr-gsm#mailing-list
and provide more info about the problem.
