### ISSUE TITLE
where is the airprobe_rtlsdr.grc shown in the video?

### ISSUE THREAD

**Issue by chakpongchung** [ptrkrysik/gr-gsm#253]
https://www.youtube.com/watch?v=Eofnb7zr8QE

I am trying to use this tool to capture the gsm packet into wireshark and then export the packets as csv file for further processing. I only have USRP and HACKRF and plan to use hackrf due to its relatively simple codebase.

I dont seem to find similar .grc in the example folder.

**Comment by ptrkrysik** [comment]
It was renamed to grgsm_livemon.grc. There is still a symbolic link 'airprobe_rtlsdr.py' pointing to 'grgsm_livemon'.
