### ISSUE TITLE
making custom block

### ISSUE THREAD

**Issue by robellebor** [ptrkrysik/gr-gsm#254]
am following the steps in https://www.nutaq.com/blog/how-make-your-own-custom-gnu-radio-blocks-part-3-c-way .... and when i execute the "make" it brings an error 

make[2]: *** [lib/CMakeFiles/gnuradio-my_module.dir/cognitive_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-my_module.dir/all] Error 2
make: *** [all] Error 2

and am using ubuntu from my flash driver

please help

**Comment by ptrkrysik** [comment]
@robellebor, please ask this question on the gr-gsm's mailing list. In
gr-gsm github issues are for submitting bugs and feature requests. Also,
if you are not interested in adding gnuradio block to gr-gsm or a block
that cooperates with it, consider asking this question on GNU Radio's
mailing list.
