### ISSUE TITLE
Problem grgsm_livemon.grc

### ISSUE THREAD

**Issue by Anonymous002** [ptrkrysik/gr-gsm#256]
# hey # ptrkrysik how can i solve this problem

Loading: "grgsm_livemon.grc"
>>> Error: Block key "gsm_bcch_ccch_demapper" not found
>>> Error: Block key "gsm_clock_offset_control" not found
>>> Error: Block key "gsm_control_channels_decoder" not found
>>> Error: Block key "gsm_control_channels_decoder" not found
>>> Error: Block key "gsm_decryption" not found
>>> Error: Block key "gsm_input" not found
>>> Error: Block key "gsm_message_printer" not found
>>> Error: Block key "gsm_receiver" not found
>>> Error: Block key "gsm_sdcch8_demapper" not found
>>> Error: Block key "rtlsdr_source" not found
>>> Done

**Comment by Anonymous002** [comment]
problem fixed thanks 
can i use grgsm_livemon withou hackrf ??

**Comment by Alster** [comment]
Of course. What errors in output you see?

**Comment by Anonymous002** [comment]
i don't have rtl sdr or hackrf - it's just the gnuradio when i start it the radio still white there's not blue lines , please solution Alster , or tell if i missing something in installation

**Comment by Alster** [comment]
For gotting "blue lines" GNU Radio must have some input like hackrf, rtlsdr, airspy, usrp, bladerf or other stuff like this. Or you can use already recorded sample located in "test_data" folder. See [wiki ](https://github.com/ptrkrysik/gr-gsm/wiki/Usage:-Decoding-How-To) for details.
I think issue can be closed =)

**Comment by Anonymous002** [comment]
Thanks :+1:

**Comment by ptrkrysik** [comment]
You can use any device supported by GNU Radio. Even if the device is not supported by gr-osmosdr block (that supports plenty of SDR devices) you can change RTL-SDR block with any other gnuradio source block. For example if you have USRP and find UHD block more convenient - you can use it as the source of the signal for gr-gsm.

p.s. for such questions/discussions the mailing list is preferred place. Here after closing the github issue not many will see it in the future.

**Comment by belahssen** [comment]
hey ptrkrysik please show me how to install pybombs and gr-gsm 
show me what i should do or type in terminal 
i use ubuntu 16.04
