### ISSUE TITLE
block dummy_burst_filter filter error

### ISSUE THREAD

**Issue by nikosvir** [ptrkrysik/gr-gsm#261]
Hello,

I'm pretty sure I'm missing something here, but sometimes when I try to decode an already captured burst file (grgsm_decode -a 8 -s 3M -b captured.burst) I get the following error and grgsm_decode just hangs:

thread[thread-per-block[4]: <block dummy_burst_filter (2)>]: pmt_cdr: wrong_type : #t

I'm I missing something or it is a bug? If needed, I can upload the burst file somewhere.

Cheers

**Comment by s6thsense** [comment]
Hi,

I think there is a mix up about topics.
My question was asked via googlegroups. (user Willem)
https://groups.google.com/forum/?_escaped_fragment_=topic/gr-gsm/WPZFnLwua0M#!topic/gr-gsm/WPZFnLwua0M

Kind regards,
Willem


nikosvir schreef op 2017-02-27 23:12:

**Comment by romankh** [comment]
@nikosvir: could be a bug, please provide the burst file for debugging.
Thank you.

**Comment by ptrkrysik** [comment]
Please provide a recipe how to reproduce this bug. I will reopen the issue then.
