### ISSUE TITLE
ubuntu14.04  on vmware

### ISSUE THREAD

**Issue by Mitchell1314** [ptrkrysik/gr-gsm#264]
Hi sir,
       I have installed gr-gsm on ubuntu14.04 on vmware, but I have got nothing:
![image](https://cloud.githubusercontent.com/assets/15179223/23596372/d5beb5c0-0264-11e7-8867-62b49c304507.png)
what can I do to fix this? 
      What's more, I want to install gr-gsm on RaspberryPi 3 with ubuntu mate 16. Can I do this?

**Comment by Robert-steve** [comment]
are you using an rtl-sdr or a usurp?
I would suggest to try grgsm_livemon first to see if you are capturing any signal.

**Comment by Mitchell1314** [comment]
Hi sir,
    I have ran "grgsm_scanner" with hackrf. When I ran "kal -s GSM900 -g 40"，I can get the result:
![image](https://cloud.githubusercontent.com/assets/15179223/23749865/37107b90-0505-11e7-9478-074f250f1326.png)
But when I ran "grgsm_scanner" ,I have got nothing:
![image](https://cloud.githubusercontent.com/assets/15179223/23749966/c2308b2a-0505-11e7-89d7-7a95b6087525.png)

By the way, the result of running "grgsm_livemon" is as follow:
![image](https://cloud.githubusercontent.com/assets/15179223/23750058/1ff7c0b6-0506-11e7-8107-f81608b1bcff.png)

What can I do to fix this? Thank you. Waiting for your reply.

**Comment by Robert-steve** [comment]
when you set the frequency in grgsm_livemon to a frequency where there is a BTS broadcasting channel, do you get any data ? If you do not get any data then maybe you should set the samp_rate to a value other than the default.

**Comment by Mitchell1314** [comment]
I set the frequency to 95.4e6, and i get the result as follows:
![image](https://cloud.githubusercontent.com/assets/15179223/23751815/e796a81a-050d-11e7-9f8d-90697b2b7b4f.png)

**Comment by Robert-steve** [comment]
it should be 954e6 instead of 95.4e6

**Comment by ptrkrysik** [comment]
Generally it isn't recommended to use gr-gsm inside virtual machine.

However you... did you try to change frequency correction (ppm) in the
grgsm_livemon? The offsets computed by kal don't look very reliable but
some of them are quite large.

P.S. Can you use the mailing list to continue this topic:
https://github.com/ptrkrysik/gr-gsm#mailing-list ? :)
