### ISSUE TITLE
HELP Please ! 

### ISSUE THREAD

**Issue by belahssen** [ptrkrysik/gr-gsm#274]
guys i don't have any device like hackrf or rtl-sdr or airspy because in my country it's dangerous to make one of them 
u can go to prison if u make one of these device 
so please help what i should do to sniffing gsm 
i try without devices and there's no blue lignes //==> so please help me !

**Comment by ptrkrysik** [comment]
This is place for feature requests and (probable) bug reports related
directly to grgsm.

Fixing the legal system of your country is beyond our capabilities.
Especially when even for possessing RTL-SDR device, which is a DVB-T
receiving USB dongle sold in most computer shops, you can go to prison.
