### ISSUE TITLE
Mobile Sniffer

### ISSUE THREAD

**Issue by julew** [ptrkrysik/gr-gsm#275]
Hi,
I would like to develop a mobile phone detector. I only want to see the mobile phones around me. My questions are:

1) Do you think that i can make it with grgsm_livemon?
2) Even the mobile phones are now 3G or 4G (lte), are they still sending GSM broadcast packets?

Thanks,

**Comment by ptrkrysik** [comment]
Hi @julew,

For sure grgsm_livemon won't do detection of phones. With exisiting gr-gsm blocks you might be able to prepare something that you want - i.e. by checking if you are able to decode data from phones. But if you want to be able to at least distinguish phones you will have to put much more work into this topic. And if you want to detect all traffic from phones - it will require significant work as well.

As for the second question - I don't know the answer.

p.s. please use mailinglist for such questions: https://github.com/ptrkrysik/gr-gsm#mailing-list
