### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by thejunaid** [ptrkrysik/gr-gsm#278]
i updated repositories of gr-gsm. then tried running gr-gsm livemon.grc and it resulted into segmentation fault.

**Comment by ptrkrysik** [comment]
Segmentation faults are ofter result of a problem with installation of
GNU Radio/gr-osmosdr. I.e. mixing of source installation with packages
installed from distribution's repository can cause that. Usually
removing GNU Radio and its libraries and reinstalling it from the
beginning helps to solve such problems.
