### ISSUE TITLE
PCS1900

### ISSUE THREAD

**Issue by xietian1** [ptrkrysik/gr-gsm#279]
Hello, have you successfully decoded the frequency in the band of PCS 1900 by HackRF One? 
Currently, I'm working on a T-Mobile card and it only had the frequency in PCS1900. However, after I set the frequency, it can't decode the signal. What should I do now? Besides, I used QXDM to check that there are several severing cells nearby. But I can't find any frequency by kalibrate-hackrf. Thanks for any help!

**Comment by ptrkrysik** [comment]
I haven't decoded PCS 1900 but there shouldn't be any substantial
differences if this there is in fact GSM signal in there. What exactly
you tried to do with gr-gsm that didn't work?
