### ISSUE TITLE
No module named grgsm

### ISSUE THREAD

**Issue by themullet** [ptrkrysik/gr-gsm#28]
Hi there, just tried installing using:

sudo ./pybombs install gr-gsm

When I go to run airprobe_rtlsdr.py getting the error: 

Traceback (most recent call last):
  File "/home/steveswallow/target/bin/airprobe_rtlsdr.py", line 19, in <module>
    import grgsm
ImportError: No module named grgsm

Same thing with airprobe_file as well. 

My python version is Python 2.7.6. 

Cheers

**Comment by ptrkrysik** [comment]
Do you have /usr/local/lib/python2.7/dist-packages/grgsm directory?
try also:
sudo ldconfig

**Comment by themullet** [comment]
perfect, got it, moved package to that directory and also moved libgnuradio-gsm.so and worked perfectly. Thanks for the help.

**Comment by henrycaga** [comment]
hi, im also getting this kind of error.. i dont have a "grgsm" folder in /usr/local/lib/python2.7/dist-packages

need help. thank you

**Comment by ptrkrysik** [comment]
If you don't have that directory either you didn't install gr-gsm or made a mistake when configuring pyboms and set installation path into directory other than /usr/local

**Comment by henrycaga** [comment]
hi sir, thanks for the reply. i forgot to update this. i already installed the gr-gsm by using the /usr/local prefix at pybombs config. its already solved. im now running the gr-gsm on odroid :) thanks a lot sir

**Comment by henrycaga** [comment]
more power on this code. keep it up. very useful thumbs up to airprobe / gr-gsm

**Comment by phocean** [comment]
Hi guys,

I also had this issue on Fedora, but the solutions I have seen so far in this thread are not optimal.
If the libs are not found on your system, then you need to adjust your environment.

Concerning the libs, make sure that ldconfig works against the local folder.
Just add the path to /etc/ldconfig.conf, or, better, create a simple file like this:
```shell
% cat /etc/ld.so.conf.d/gr-gsm.conf 
/usr/local/lib64
```

Similarly for Python, add the following line in your $HOME/.bashrc or $HOME/.zshrc:
```shell
PYTHONPATH=$PYTHONPATH:/usr/local/lib64/python2.7/site-packages/
export PYTHONPATH
```

I hope this helps :-)

**Comment by tiger762** [comment]
I'm also having this problem, but none of the suggestions has worked for me. I have PYTHONPATH defined as /usr/local/lib64/python2.7/site-packages/

I did the manual build, as PyBOMBS is always a nightmare for me for some reason. I did this:

git clone https://github.com/ptrkrysik/gr-gsm
cd gr-gsm
mkdir build
cd build
cmake ..
make
make install

It appeared to build fine, but I am wondering if "swig" did not get built, because under $PYTHONPATH there is nothing resembling SWIG.

**Comment by attina** [comment]
I fixed same problem by following command on Fedora 25, hope this can help you guys.

```
export PYTHONPATH=$PYTHONPATH:/usr/local/lib64/python2.7/site-packages/grgsm:/usr/local/lib64/python2.7/site-packages
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64/
```
output:

> linux; GNU C++ version 6.2.1 20160916 (Red Hat 6.2.1-2); Boost_106000; UHD_003.010.001.000-0-unknown
>ARFCN:   21, Freq:  939.2M, CID: 58453, LAC:  4544, MCC: 460, MNC:   0, Pwr: -29
>ARFCN:   33, Freq:  941.6M, CID:  8393, LAC:  4530, MCC: 460, MNC:   0, Pwr: -27
>ARFCN:   36, Freq:  942.2M, CID: 57566, LAC:  4530, MCC: 460, MNC:   0, Pwr: -49
>ARFCN:   38, Freq:  942.6M, CID:     0, LAC:  4530, MCC: 460, MNC:   0, Pwr: -39
>ARFCN:  122, Freq:  959.4M, CID: 45883, LAC:  4309, MCC: 460, MNC:   1, Pwr: -28

**Comment by Lohith12** [comment]
ModuleNotFoundError: No module named 'grgsm' . Please help

**Comment by catalinalb** [comment]
> ModuleNotFoundError: No module named 'grgsm' . Please help

Same on ubuntu 18.04 installation with pybombs

**Comment by velichkov** [comment]
Hi @Lohith12, @catalinalb,

> ModuleNotFoundError: No module named 'grgsm' . Please help

In case you are using gnuradio 3.8 with python 3 try adding `/usr/local/lib/python3/dist-packages/` to `PYTHONPATH` and then from the same terminal run the grgsm commands.

```
export PYTHONPATH=/usr/local/lib/python3/dist-packages/:$PYTHONPATH
./grgsm_livemon
```

**Comment by Lohith12** [comment]
> Hi @Lohith12, @catalinalb,
> 
> > ModuleNotFoundError: No module named 'grgsm' . Please help
> 
> In case you are using gnuradio 3.8 with python 3 try adding `/usr/local/lib/python3/dist-packages/` to `PYTHONPATH` and then from the same terminal run the grgsm commands.
> 
> ```
> export PYTHONPATH=/usr/local/lib/python3/dist-packages/:$PYTHONPATH
> ./grgsm_livemon
> ```

Thanks bro it worked

**Comment by catalinalb** [comment]
How can I add this line ? where should I find PYTHONPATH ?

**Comment by velichkov** [comment]
@catalinalb,

> How can I add this line ? 

What line?

>  where should I find PYTHONPATH ?

`PYTHONPATH` is an environment variable. Open a terminal end execute `echo $PYTHONPATH`

**Comment by batica81** [comment]
Form me on Debian 11, this path actually worked:

export PYTHONPATH=/usr/local/lib/python3.9/site-packages/:$PYTHONPATH
