### ISSUE TITLE
Selection from Multiple Dongles 

### ISSUE THREAD

**Issue by engrmasood2002** [ptrkrysik/gr-gsm#289]
Hi,
What code segment i need to modify in gr-gsm Livemon to select rtl dongle source to be dongle #2. I  have total two dongles connected with pc now and want to connect dongle# 1 with different software.

**Comment by Alster** [comment]
`self.rtlsdr_source_0 = osmosdr.source( args="numchan=" + str(1) + " " + args )`
As you see, Osmosdr is used. Also, you can pass into `--args` argument the parameters of the device. Look how to set the right arguments for your RTL-dongle.

**Comment by ptrkrysik** [comment]
You don't need to change anything. Use --args option and pass devices serial number or just number (like --args="rtl=1")
