### ISSUE TITLE
system info extractor - arfcn always zero

### ISSUE THREAD

**Issue by romankh** [ptrkrysik/gr-gsm#30]
In extract_system_info the arfcn is used as id for the chan_info, however gsmtap header->arfcn is always zero in my case, also in Wireshark. 

Does this work for you, e.g. do you see valid arfcn values in the gsmtap header ?

**Comment by romankh** [comment]
Found out that i needed to set the arfcn in the constructor via cell_allocation

**Comment by mrtylmz1007** [comment]
Could you explain in detail please? I face this problem too and I couldn't solve it yet

**Comment by romankh** [comment]
Open the flowgraph in Gnuradio Companion, and double click the GSM Receiver. There you can set the property cell allocation. Set the ARFCN inside the brackets, like `[29]` for ARFCN 29.

**Comment by mrtylmz1007** [comment]
Thanks a lot
