### ISSUE TITLE
How long do you plan to keep the compatibility symlinks?

### ISSUE THREAD

**Issue by petterreinholdtsen** [ptrkrysik/gr-gsm#302]
According to git, the app binary name rename happened 2016-02-13 and the compatibility symlinks have been installed since that time.  But how long do you plan to keep them?  I consider dropping these links when uploading gr-gsm to Debian as an official Debian package, and would like your feedback if you believe this is a good or horrible idea for the packages in Debian and all derived distros like Ubuntu.

**Comment by ptrkrysik** [comment]
I think it is a good idea. It is rare that someone ask about these names. It's time to get rid of them. I will remove the symlinks in the packaging branch.
