### ISSUE TITLE
Use same name for git repo and cmake project?

### ISSUE THREAD

**Issue by petterreinholdtsen** [ptrkrysik/gr-gsm#304]
Hi.  While working on the Debian packaging of gr-gsm, I noticed the documentation is installed in /usr/share/doc/gr-grgsm/, while the package I was preparing would store its documentation files in /usr/share/doc/gr-gsm/ based on the package name.  I picked the package name from the name of the git repository.  Why is the name of the git repository and the cmake project name not the same?  Would you be interested in renaming the cmake project name to be consistent with the git repo name?

This patch would implement the change I propose:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5832d42..72e5099 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -22,7 +22,7 @@
 # Project setup
 ########################################################################
 cmake_minimum_required(VERSION 2.6)
-project(gr-grgsm CXX C)
+project(gr-gsm CXX C)
 enable_testing()
 
 #set(CMAKE_BUILD_TYPE "Debug")
```

**Comment by ptrkrysik** [comment]
Changed it in the packaging branch
