### ISSUE TITLE
Unable to see decoded output of Hopping SDCCH8 channel

### ISSUE THREAD

**Issue by ppandit26** [ptrkrysik/gr-gsm#305]
I have a cfile captured at 2e6 at arfcn 79. In SI type message list of arfcns are 59,77,79.
I obtained the hopping parameters through Immediate assignment message: HSN:56 Timeslot:1 Training sequence Number:3 MAIO:0

I configured the receiver block for cell allocation list obtained from SI type 1 and Cx hopper block with MA:[55,77] HSN:56 MAIO:0.
On CX output I see GSMTAP messages for arfcns 59 and 77. After SDCCH8(Time slot 1) demapper block, I can observe the LAPDm messages in Wireshark. But I do not see any output after control channel decoder block.

![immediate_assignmentpng](https://user-images.githubusercontent.com/30795745/29207013-c24f818a-7e84-11e7-8947-9717700357e6.png)

![si_type1](https://user-images.githubusercontent.com/30795745/29207014-c251634c-7e84-11e7-8517-36cf17e5b0b6.png)

![output_after_sdcch8_demapper](https://user-images.githubusercontent.com/30795745/29207012-c24e9040-7e84-11e7-8355-03fa6e0ea934.png)

Can anyone kindly provide me with some inputs or suggestions as to how can I proceed?

Thank You!

**Comment by ppandit26** [comment]
An update to this issue:
I noticed that the arfcn(79) on which the cfile was captured also has to be included in the MA list.
The MA in Immediate assignment showed three arfcns including the main arfcn 79. I edited the flowgraph to take four inputs. One the wideband and other three for hopping(narrowband files on arfcns: 59, 77 ,79). 
Now I get the same output as shown in third image at the output of control channel decoder. But again I do not see ciphering mode command or other messages.

**Comment by ppandit26** [comment]
Hello,
An update to this issue:
I can see the ciphering mode command, CM service request and system information messages at the output of the control channel decoder. (The output though is not consistent as it is taking very long to output the messages and every run gives different output).
I am unable to see any decrypted output. The ciphering command shows A5/3 algorithm. I do have the Kc. But I am unable to see any decrypted SMS on downlink.
![hopping](https://user-images.githubusercontent.com/30795745/29710004-e2323f82-898e-11e7-8c95-2ab60d9e04fd.png)

**Comment by justhack21** [comment]
hello mam,
I am facing the same issue as you mentioned in issue 305. I am able to see LAPDm messages on wireshark demapper but nothing after control channel decoder.
Were you able to solve this. Can you please help me with this.

**Comment by moemusaa** [comment]
hi , i have the same issue , can someone help us ?
