### ISSUE TITLE
Decoding

### ISSUE THREAD

**Issue by Srg123r** [ptrkrysik/gr-gsm#310]
Hi.. I have following question:
1. After decoding BCCH, immediate assignment message needs to be looked up for getting the timeslot for decoding SDCCH. If there are more than one timeslots in different immediate assignment messages, then which one should be chosen?

Thanks

**Comment by Alster** [comment]
In short, all timeslots.
What is a timeslot?
[https://en.wikipedia.org/wiki/Time-division_multiple_access](https://en.wikipedia.org/wiki/Time-division_multiple_access)

**Comment by E3V3A** [comment]
@Srg123r  Please close the issue if it was answered or add more feedback if not.
