### ISSUE TITLE
Cant extract voice from a wideband capture

### ISSUE THREAD

**Issue by newuser55555** [ptrkrysik/gr-gsm#334]
Hi,
I am new to this gsm thing and have limited knowledge. I was trying to reproduce the freq hopping decode but i am unable to extract voice.

I have done the following,
- captured a wideband cfile
- used channelizer to get individual channels
- made a grc file to get Cx burst file
- Now when i try to extract voice i get nothing
- i have checked the CA, HSN ,TSEQ and TS values
- when i see the burst file after Cx hopper in wireshark i can see that its combining all the arfcn packets
plz help

**Comment by justhack21** [comment]
hi buddy,  seems all fine to me. Can you share your cfile and the grc files. I ll see if i can help

**Comment by justhack21** [comment]
.

**Comment by newuser55555** [comment]
got it resolved on my own brother...anyways thanks...it was a minor issue

**Comment by newuser55555** [comment]
do you have any idea if AMR can be decoded

**Comment by justhack21** [comment]
Yes it is very much possible. If you have some cfiles with AMR coded audio I ll help you out with them.

**Comment by b4ss3k** [comment]
hi, have a question, how you capture in wideband cfile? what hardware do you use?

**Comment by ptrkrysik** [comment]
Hi guys, some rates of AMR can be decoded (i.e. 12.2kbit/s), some can't. In case you want to continue the discussion do it here: #226.
