### ISSUE TITLE
Add arfcn reporting to grgsm_livemon too?

### ISSUE THREAD

**Issue by petterreinholdtsen** [ptrkrysik/gr-gsm#337]
In commit 3dfa11b89e6a74e6857c11e3029b372c746d535f, arfcn reporting was added to grgsm_livemon_headless.  Could that change be added to grgsm_livemon too?  Without it, grgsm_livemon always report 0 in the arfcn field in the gsmtap header.

**Comment by ptrkrysik** [comment]
Closed by your pull request #339.
