### ISSUE TITLE
Hello! Has anyone ported this to use an Ettus B200 (UHD/USRP)?

### ISSUE THREAD

**Issue by tiger762** [ptrkrysik/gr-gsm#347]
I ask because where I live, the only 2G GSM service is T-Mobile and it is at 1969.4 MHz (ARFCN 708) well outside the reach of an RTL-SDR :( Thanks!

**Comment by axilirator** [comment]
Yes, the USRP hardware is supported. Make sure you have GNU Radio with UHD support compiled in.
Tip: gnuradio-config-info --enabled-components

**Comment by Keskebeu** [comment]
Oh yea
