### ISSUE TITLE
use libosmocoding AMR decoder

### ISSUE THREAD

**Issue by justforfun11** [ptrkrysik/gr-gsm#354]
How can libosmocoding AMR decoder from gsm0503 be used for full rate AMR.

I have been trying to use this function:
gsm0503_tch_afs_decode(frameBuffer, bursts_s, 0, codec, 4, &ft, &cmr, &n_errors, &n_bits_total);
		    
But the output file gives a garbled voice.

Please help. How to use this function in tch_f decoder

**Comment by AlexeyGS** [comment]
This is because the function returns only payload without a header. You must manually add a header for each codec. For all codecs, header is 0x3c, but for AMR 5.9 header is 0x14.

**Comment by dabadee** [comment]
Hi justofrfun11, did you have any luck with using libosmocoding AMR decoder ?

**Comment by justforfun11** [comment]
no luck yet buddy

**Comment by justforfun11** [comment]
@ AlexeyGS just curious...if this thing works out, will the same thing work for half rate if proper demapping is done

**Comment by AlexeyGS** [comment]
@justforfun11 I use the libosmocore functions and it`s work fine for the tch/f channel. But for tch/h channel I can`t get results yet. Maybe I wrote the tch/h demapper incorrectly.

**Comment by dabadee** [comment]
@AlexeyGS can you please send your code where you are using libosmocoding for tch/f channel, or may be upload it on your GitHub. I am trying to integrate both of these gsm0503_tch_afs_decode and gsm0503_tch_ahs_decode but not having any success.

**Comment by justforfun11** [comment]
@ AlexeyGS 
Thanks, I was able to the integration....header was the issue as u said. 
Demapper for the half rate is ready with me and its working fine. But still the voice is garbled.
Any suggestions.

**Comment by justforfun11** [comment]
@dabadee i could finally make that integration work

**Comment by dabadee** [comment]
@justforfun11 that's great news. Can you please share your code, may be put it on GitHub ? I can check it on the AMR HR files I have and give you feedback. Also did you check if you are getting 0 in "n_errors" from the gsm0503_tch_ahs_decode function ?

**Comment by djks74** [comment]
Hi @justforfun11 ,
can you share demapper/decoder for TCHF/TCHH please?
and all fellows here can decode TCHF voice?

My self never get succes to decode TCHF voice. so please help.....

Thanks,
DUO

**Comment by dabadee** [comment]
Any updates ?

**Comment by ptrkrysik** [comment]
Hi all, issues with AMR are known #226. In case you want to discuss enhancing AMR support please do it in  that issue or on the mailing-list.
