### ISSUE TITLE
problem with 'libosmocore' on macOS while compiling. 'make' throws errors

### ISSUE THREAD

**Issue by KirilShishkoski** [ptrkrysik/gr-gsm#356]
Hi,
I'm running a macOS here. I'm trying to compile gr-gsm manually because with 'sudo pybombs install gr-gsm' I'm getting the following error: 

PyBOMBS.install_manager - ERROR - Package has no install method: libudev

and manually I managed to install all dependencies except for the libosmocore. Here what happens:

 autoreconf -i
./configure

(up to here works ok)

make

(after 'make' is executed) it throws me these errors:

![screen shot 2017-12-15 at 3 38 00 am](https://user-images.githubusercontent.com/16950917/34024284-8bd641f2-e149-11e7-9f96-66b4b7f1bf3e.png)
![screen shot 2017-12-15 at 3 38 59 am](https://user-images.githubusercontent.com/16950917/34024285-8bfe0d90-e149-11e7-8ca4-eb5bc7914927.png)

Anyone has an idea what might be the problem?

**Comment by velichkov** [comment]
Hi @KirilShishkoski,

I don't have access to macOS system right now so I can't really help you but have you tried to report the problem to the osmocom project first? 

http://git.osmocom.org/libosmocore/about/
> Discussions related to libosmocore are happening on the openbsc@lists.osmocom.org mailing list, please see https://lists.osmocom.org/mailman/listinfo/openbsc for subscription options and the list archive.

P.S.
And please when reporting issues upload the full build log together with all install/build steps you have executed and not just few screen shots.

BR

**Comment by KirilShishkoski** [comment]
Fixed it with brew tap from one of these dirs (don't remember which was exactly try both):

nejohnson2/homebrew-sdr
or
dholm/homebrew-sdr

**Comment by codexofc** [comment]
hi men i have similar error can you help me please
