### ISSUE TITLE
AtributeError

### ISSUE THREAD

**Issue by OGThug** [ptrkrysik/gr-gsm#359]
#python /opt/gr-gsm/apps/grgsm_livemon.py

linux; GNU C++ version 7.2.0; Boost_106200; UHD_003.010.002.000-0-unknown

Traceback (most recent call last):
  File "/opt/gr-gsm/apps/grgsm_livemon.py", line 354, in <module>
    main()
  File "/opt/gr-gsm/apps/grgsm_livemon.py", line 342, in main
    tb = top_block_cls(args=options.args, collector=options.collector, collectorport=options.collectorport, fc=options.fc, gain=options.gain, osr=options.osr, ppm=options.ppm, samp_rate=options.samp_rate, serverport=options.serverport, shiftoff=options.shiftoff)
  File "/opt/gr-gsm/apps/grgsm_livemon.py", line 64, in __init__
    self.restoreGeometry(self.settings.value("geometry").toByteArray())
AttributeError: 'NoneType' object has no attribute 'toByteArray'

{
kali-rolling: 
}

**Comment by velichkov** [comment]
Hi @OGThug,

See comments in #355. Also try to uninstall the version you've compiled and install both `gnuradio` and `gr-gsm` from the kali apt repository.
