### ISSUE TITLE
got this error :Error installing package libosmocore. Aborting

### ISSUE THREAD

**Issue by TAPAN1539** [ptrkrysik/gr-gsm#364]
got this error :Error installing package libosmocore. Aborting

**Comment by velichkov** [comment]
Hi @TAPAN1539 

Try to install `gnutls-dev` package if you are using a Debian based distribution.
 
If this doesn't help provide some more logs (the last 20 - 30 lines for example) and the full version of the  distribution you are using as it's rather difficult to help you having only a single error message.

**Comment by ptrkrysik** [comment]
@TAPAN1539 , I'm closing this thread due to lack of more detailed description of the problem. 

@velichkov, many thanks for lots of support and help from you to the gr-gsm users :) . For example in this case I wouldn't be able to give any advice.
