### ISSUE TITLE
malformed packet alwayes appear in SMS CP-DATA

### ISSUE THREAD

**Issue by moemusaa** [ptrkrysik/gr-gsm#367]
Hi , everyone 
i have a problem for decoding hopping SDCCH8 channel.

first listen to BCCH C0 i have this

![a](https://user-images.githubusercontent.com/34807084/34905176-4b195af8-f85c-11e7-87af-e854caecd417.png)

from immediate assignment : 
MAIO : 0
HSN   : 25
TSEQ : 2
Timeslot : 2

and From SI type 1 , i found List of ARFCNs = 648 673 676 683

then i configure Cx blocker as previous information 
EDIT " add 648 to MA in Cx block"

![c](https://user-images.githubusercontent.com/34807084/34905223-f0969c84-f85c-11e7-989e-41b2f877531b.png)

after i decrypt SDCCH8 with Kc , every thing goes OK , But the SMS CP-DATA going wrong with malformed packet :( 

![q](https://user-images.githubusercontent.com/34807084/34945040-87709cbe-fa0a-11e7-8936-503230850448.png)

i try to send another msg 3 time , and have same problem 

please help :)

**Comment by moemusaa** [comment]
I solve the first problem , by adding main ARFCN " which is 648 " into Cx block inside MA .
i decrypt the SDCCH  , i have CM service request with Sender TMSI , " SMS CP-ACK" ,  and msg label as connect 

![q](https://user-images.githubusercontent.com/34807084/34935630-313778b8-f9e7-11e7-9e19-8cd5fff14c9f.png)

the problem here i cant find the SMS , also why this "malformed packet" always show 

please help :)

**Comment by velichkov** [comment]
Hi @moemusaa,

Try with wireshark version 2.2.6 or older. See https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14105

**Comment by moemusaa** [comment]
thank @velichkov for replay
But when i try to decode non hopping channel its going fine with me , and i can see SMS CP-DATA with no problem
the problem only appear in hopping channel

**Comment by ptrkrysik** [comment]
@moemusaa - can you show your mobile allocation from immediate assignment command?
