### ISSUE TITLE
convert brust file to cfile

### ISSUE THREAD

**Issue by moemusaa** [ptrkrysik/gr-gsm#371]
Hi everyone 

i need to know if there are any way to convert from brust file to cfile   ? 

and another Question : 

when i capture wide data into cfile format , and then using grgsm_channlize and then decode output file as cfile , everything goes fine. But when i try same thing with Brust format , nothing appear at wireshark :(

**Comment by ptrkrysik** [comment]
Hi @moemusaa, please use the mailing-list https://github.com/ptrkrysik/gr-gsm#mailing-list and please try describe a bit more what you are trying to do exactly with the bursts files. From what you've written it seems that you trying to channelize them like signal files.
