### ISSUE TITLE
Need of C0 in hopping

### ISSUE THREAD

**Issue by dabadee** [ptrkrysik/gr-gsm#373]
Ok I have had some success decoding hopping channels, and it works fine on some networks.

On some other networks I am confused how to use the GSM Receiver block. I am facing the following scenario:

1. There is a ARFCN in EGSM-900 band, which I listen too, and on SDCCH8, I get Assignment Command that gives the List of ARFCNs, having 4 ARFCNS in DCS1800 band.
2. Now my SDR allows to capture 30Mhz easily, and so I capture a portion of DCS1800 band and channelize it to retrieve my desired ARFCNs
3. Now what should I put at the C0 channel ? (I tried capturing the ARFCN in EGSM900 band on which the BCCH is running and where I received the Assignment command, using a RTL-SDR, while the other SDR captured the DCS1800 band, but I guess the two SDRs captures aren't synchronized and so hopping doesnt work)
Also is it necessary to provide C0 channel, as the first argument in Cell Allocation in GSM Receiver block ?

**Comment by ptrkrysik** [comment]
As currently C0 channel is used in the GSM Receiver for synchronization you will have to capture it C0 on GSM900 band synchronously with your GSM1800 hopping channels. Using another non-synchronized receiver to capture it is not a solution - you will need to synchronize it somehow first. If you intend to continue this discussion - please do it on the mailing-list: https://github.com/ptrkrysik/gr-gsm#mailing-list
