### ISSUE TITLE
problem with pyqt error

### ISSUE THREAD

**Issue by vequeemnhe** [ptrkrysik/gr-gsm#377]

**Comment by velichkov** [comment]
Hi @vequeemnhe,

> AttributeError: 'module' object has no attribute 'QWidget'

See https://github.com/ptrkrysik/gr-gsm/issues/355#issuecomment-366277650 and https://github.com/ptrkrysik/gr-gsm/issues/355#issuecomment-356401976

What happened with the other issue #376. If you have resolved it please write how and close it.
 
P.S.
If possible next time before opening issues try to search first
https://github.com/ptrkrysik/gr-gsm/search?q=AttributeError%3A+%27module%27+object+has+no+attribute+%27QWidget%27&type=Issues&utf8=%E2%9C%93
