### ISSUE TITLE
grgsm_livemon

### ISSUE THREAD

**Issue by gronget** [ptrkrysik/gr-gsm#381]
Hey. what could not be happening here......this happens when i run grgsm_livemon

Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 51, in <module>
    import grgsm
  File "/usr/local/lib/python2.7/dist-packages/grgsm/__init__.py", line 45, in <module>
    from grgsm_swig import *
  File "/usr/local/lib/python2.7/dist-packages/grgsm/grgsm_swig.py", line 28, in <module>
    _grgsm_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/grgsm/grgsm_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_grgsm_swig', fp, pathname, description)
ImportError: libgnutls.so.28: cannot open shared object file: No such file or directory

**Comment by velichkov** [comment]
Hi @gronget,

Which Linux distribution and version you are using?
How did you installed the `grgsm` - using `pybombs` or manually?

> ImportError: libgnutls.so.28: cannot open shared object file: No such file or directory

As stated in the error message it can't find the `libgnutls.so.28` library, first try to find it manually
```
find / -name libgnutls.so.28
```
and then add the path where it is located to the LD_LIBRARY_PATH environment variable
 For example if it is `/usr/local/lib/` then execute
```
LD_LIBRARY_PATH=/usr/local/lib/ grgsm_livemon
```

**Comment by gronget** [comment]
sorry for the late reply
it was a manual installation
I upgraded from ubuntu 14.04 to 16.04 TS ..

**Comment by velichkov** [comment]
So have you found the `libgnutls.so.28` and have you tried to add this path to LD_LIBRARY_PATH?

**Comment by gronget** [comment]
oh woow.
success....     overcome that by executing apps/grgsm_livemon.grc through gnuradio-companion

Thanks
