### ISSUE TITLE
*** Error in `/usr/bin/python2': corrupted double-linked list: 0x01c22b08 ***

### ISSUE THREAD

**Issue by imranrajjad** [ptrkrysik/gr-gsm#383]
I am trying to get gr-gsm to work on Pi3. After following the complete documentation, I am unable to start grgsm_headless. Below is the error I get

```
pi@EL-raspberrypi:~ $ grgsm_livemon_headless -f 936.4M -g 40.2 -p 37
linux; GNU C++ version 6.2.0 20161010; Boost_106100; UHD_003.009.005-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.10
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya
*** Error in `/usr/bin/python2': corrupted double-linked list: 0x01c22b08 ***
Aborted

```

Any idea what might be broken?

thanks

**Comment by Gheek** [comment]
Exact the same Problem for me; seems to be a issue related to the build process.

**Comment by offle** [comment]
Same here :(

**Comment by imranrajjad** [comment]
guys use Ubuntu-mate

**Comment by velichkov** [comment]
Hi @AgeOfMarcus 

See https://github.com/ptrkrysik/gr-gsm/issues/435#issuecomment-440987611

> To run the grgsm code you also need to specify --args rtl, otherwise you get error message, compare to desktop version where this is not needed.
