### ISSUE TITLE
got this error : jack server is not running or cannot be started

### ISSUE THREAD

**Issue by zhongrui960326** [ptrkrysik/gr-gsm#385]
Hi! I am new to this field and recently I've been installing gr-gsm on Kali with usrp N210.
Here is the issue, while I am using the command.

> grgsm_capture -g 40 -a 12 -s 1000000 -c sms.cfile -T 20

I encountered this error:

> gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
> built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Thank you guys so much!

**Comment by velichkov** [comment]
Hi @zhongrui960326,

> Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

These are harmless errors and you could just safely ignore them.

To resolve them you need to specify the device, for USRP it is `--args=uhd` 
```
grgsm_capture --args=uhd -g 40 -a 12 -s 1000000 -c sms.cfile -T 20
```
