### ISSUE TITLE
gr-gsm scanner  deep 

### ISSUE THREAD

**Issue by mazen-bassiouny** [ptrkrysik/gr-gsm#406]
Dears,
I am trying to use the scanner APP to scan the available cells , but i want to know what is happening inside the GSM receiver exactly , how can it sense the FCCH channel , where is this part in code ?? how the synchronization is done ? would we need to build complete receiver like that to just scan the BCCH or some functions can be removed.. i just want some details how it is working .... i tried to read the code but it is very difficult to understand what is happening...

**Comment by ptrkrysik** [comment]
Hi @mazen-bassiouny, please ask the question on the mailing list https://github.com/ptrkrysik/gr-gsm#mailing-list. I will try to help you then.
