### ISSUE TITLE
Question about terminal output

### ISSUE THREAD

**Issue by thewizkid87** [ptrkrysik/gr-gsm#407]
Hi @ptrkrysik 

I am currently learning about GSM and have been using your code, first of i would like to say thanks :-)

I am using "grgsm_livemon_headless" and want to know is there a way to turn off the output of the data to the terminal?

I dont mind modifying the code to accomplish this.

I looked in the code and saw that you are using "gr.top_block"
then passing the params, and calling its start function.

I could not find good documentation on gr.top_block so was having a hard time achieving my goal.

Any input will be greatly appreciated.

Thanks

**Comment by ptrkrysik** [comment]
Please ask on the mailing list: https://github.com/ptrkrysik/gr-gsm#mailing-list
