### ISSUE TITLE
GSMTAP Signal Level = 0

### ISSUE THREAD

**Issue by pawelbytniewski** [ptrkrysik/gr-gsm#41]
Hi,
I've been using gr-gsm for a while now on E4000 based dongle and it's great, however when I'm looking at packets in wireshark every single one of them has signal level equal to 0 in GSM TAP header. Is that intended? (NSR values range from 220 to 228)

**Comment by ptrkrysik** [comment]
There are two factors in here. First: SNR and signal level in Wireshark are swapped in relation to gsmtap.h header.

Second - SNR is not computed in gr-gsm as I didn't come up with any algorithm to do this yet. Signal level is computed - but it's not calibrated value in absolute units yet.
