### ISSUE TITLE
NO SUPPORTED DEVICES FOUND TO PICK FROM - GRC - UBUNTU 16.04 LTS

### ISSUE THREAD

**Issue by aecs18** [ptrkrysik/gr-gsm#423]
Good morning everyone.

I write here to see if any of you know what installation errors I may have had to use the r820t2 in gnu radio companion.

I'm trying to make an FM receiver and other analog TV receiver but when running the program does not receive any type of signal and the view errors, I have: devices not supported. I believe that this is some driver to be installed but I don't know where or how.

The steps that I have followed for installation (Ubuntu 16.04 LTS) have been:

sudo apt-get update
sudo apt-get install git
sudo apt-get install cmake
sudo apt-get install build-essential
sudo apt-get install libusb-1.0-0-dev

git clone git://git.osmocom.org/rtl-sdr.git
cd rtl-sdr/
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig
sudo cp ../rtl-sdr.rules /etc/udev/rules.d/

Opening /etc/modprobe.d folder 
Creating a new file 'blacklist-rtl.conf' and add this one line:
blacklist dvb_usb_rtl28xxu

rtl_test -t 

After that, the sytem recognizes the RTL source and I can listen the radio with this command, but GRC says the same error: FATAL: No supported devices found to pick from.
rtl_fm -f 89.2e6 -M wbfm -s 200000 -r 48000 - | aplay -r 48k -f S16_LE

I tried to install everything again using Synaptic too, but the error still exists.

Please, if any of you know that i need to install It would serve as much help as I am a novice programmer and i need to resolve this problem for my project.

![captura de pantalla de 2018-08-04 09-23-45](https://user-images.githubusercontent.com/41928718/43677186-bdb59e1e-97cb-11e8-8e72-7e55850bfa7d.png)
![captura de pantalla de 2018-08-04 09-31-20](https://user-images.githubusercontent.com/41928718/43677188-c254e4c0-97cb-11e8-848c-f5ff05991d28.png)
![captura de pantalla de 2018-08-02 21-09-24](https://user-images.githubusercontent.com/41928718/43677199-ff21b900-97cb-11e8-8064-37f68a3bd8d0.png)
![captura de pantalla de 2018-08-02 21-09-32](https://user-images.githubusercontent.com/41928718/43677200-ff3ff7a8-97cb-11e8-949b-17fa6135c19f.png)
![captura de pantalla de 2018-08-02 21-09-39](https://user-images.githubusercontent.com/41928718/43677201-ff5d60cc-97cb-11e8-8c49-ada9694ed79b.png)
![captura de pantalla de 2018-08-02 21-09-44](https://user-images.githubusercontent.com/41928718/43677202-ff9aae50-97cb-11e8-972b-092ffdee9fef.png)
![captura de pantalla de 2018-08-02 21-10-01](https://user-images.githubusercontent.com/41928718/43677203-00901ec6-97cc-11e8-83ad-9c5788b0932b.png)
![captura de pantalla de 2018-08-02 21-10-05](https://user-images.githubusercontent.com/41928718/43677204-019a7a32-97cc-11e8-80f5-fc0d19c1ac9e.png)
![captura de pantalla de 2018-08-02 21-15-54](https://user-images.githubusercontent.com/41928718/43677205-032793ee-97cc-11e8-90df-3d7ad126a3c1.png)
![captura de pantalla de 2018-08-02 21-22-12](https://user-images.githubusercontent.com/41928718/43677206-039fdebc-97cc-11e8-8b4b-cc17c2b295a9.png)
![captura de pantalla de 2018-08-03 20-20-35](https://user-images.githubusercontent.com/41928718/43677219-40a43ee8-97cc-11e8-85ea-fe719a76aadb.png)
![captura de pantalla de 2018-08-03 20-30-48](https://user-images.githubusercontent.com/41928718/43677224-4f2ed57c-97cc-11e8-920d-ecaed369200e.png)
![captura de pantalla de 2018-08-04 09-55-07](https://user-images.githubusercontent.com/41928718/43677237-8ccfafa0-97cc-11e8-897f-ea3f15d56b9e.png)
![captura de pantalla de 2018-08-04 09-55-18](https://user-images.githubusercontent.com/41928718/43677238-8cef2c90-97cc-11e8-9575-a8ad5a92039c.png)

**Comment by ptrkrysik** [comment]
Hi, I'm closing it as it doesn't seem to be gr-gsm's bug. Anyway - you can try installation described here:
https://osmocom.org/projects/gr-gsm/wiki/Installation#Debbian-based-distributions-Debian-Testing-Ubuntu-1604-Kali-Rolling-Edition

(remember to remove what you installed manually, i.e. rtl-sdr)

In case the problem persist you can ask for help on https://github.com/ptrkrysik/gr-gsm#mailing-list (you can link this issue to avoid rewriting everything there).
