### ISSUE TITLE
Problem when run grgsm_livemon and gnuradio-companion airprobertlsdr.grc

### ISSUE THREAD

**Issue by hoalan1984** [ptrkrysik/gr-gsm#424]
i've install gr-gsm on my ubuntu 16.04 but it alway show out error. Please tell me how to resolve it. Thanks you...
![inform2](https://user-images.githubusercontent.com/11917204/43755825-1903b05e-9a3c-11e8-992d-a328a3767848.png)

**Comment by velichkov** [comment]
Hi @hoalan1984,

Please never upload screenshots of your terminal, you could select the text, then right click, copy and paste the text.

It seems you've installed the gnuradio and gr-gsm using pybombs, which is the most error prone method. My advice is to remove everything installed by pybombs and install according to the [new wiki](https://osmocom.org/projects/gr-gsm/wiki/Installation#Debbian-based-distributions-Debian-Testing-Ubuntu-1604-Kali-Rolling-Edition)

**Comment by hoalan1984** [comment]
Thank you so much....i'll never upload screenshoot later.
