### ISSUE TITLE
grgsm_livemon generating segmentation fault

### ISSUE THREAD

**Issue by Sh0ckFR** [ptrkrysik/gr-gsm#427]
Hello,

I tried to use this guide on a fresh Kali rolling version : [https://osmocom.org/projects/gr-gsm/wiki/Installation](https://osmocom.org/projects/gr-gsm/wiki/Installation)

But I have an issue during the generation:

`
[ 89%] Generating grgsm_livemon
Segmentation fault
make[2]: *** [apps/CMakeFiles/pygen_apps.dir/build.make:82: apps/grgsm_livemon] Error 1
make[1]: *** [CMakeFiles/Makefile2:1173: apps/CMakeFiles/pygen_apps.dir/all] Error 2
make: *** [Makefile:127: all] Error 2
`

I removed all the osmosdr, gr-gsm packages multiple times but no way, if I try to install the debian package directly, I have the same issue than : [https://github.com/ptrkrysik/gr-gsm/issues/426](https://github.com/ptrkrysik/gr-gsm/issues/426)

So I don't really understand what is wrong, my hardware is not a hackrf but a rtl2832 dvb-t adapter.

Here is my system informations :

debian-version: kali-rolling
gnuradio version: 3.7.13.4-1
grcc path: /usr/local/bin/grcc
cmake version: 3.2.0

I also removed pybombs and the pip package gr-gsm.

The last logs:

`
[ 88%] Generating __init__.pyo, udp_link.pyo, ctrl_if.pyo, ctrl_if_bb.pyo, fake_pm.pyo, radio_if.pyo, radio_if_grc.pyo, change_sign_of_dict_elements.pyo
cd /home/shock/gr-gsm/build/python/trx && /usr/bin/python2 -O /home/shock/gr-gsm/build/python_compile_helper.py /home/shock/gr-gsm/python/trx/__init__.py /home/shock/gr-gsm/python/trx/udp_link.py /home/shock/gr-gsm/python/trx/ctrl_if.py /home/shock/gr-gsm/python/trx/ctrl_if_bb.py /home/shock/gr-gsm/python/trx/fake_pm.py /home/shock/gr-gsm/python/trx/radio_if.py /home/shock/gr-gsm/python/trx/radio_if_grc.py /home/shock/gr-gsm/python/trx/change_sign_of_dict_elements.py /home/shock/gr-gsm/build/python/trx/__init__.pyo /home/shock/gr-gsm/build/python/trx/udp_link.pyo /home/shock/gr-gsm/build/python/trx/ctrl_if.pyo /home/shock/gr-gsm/build/python/trx/ctrl_if_bb.pyo /home/shock/gr-gsm/build/python/trx/fake_pm.pyo /home/shock/gr-gsm/build/python/trx/radio_if.pyo /home/shock/gr-gsm/build/python/trx/radio_if_grc.pyo /home/shock/gr-gsm/build/python/trx/change_sign_of_dict_elements.pyo
make[2]: Leaving directory '/home/shock/gr-gsm/build'
/usr/local/bin/cmake -E cmake_progress_report /home/shock/gr-gsm/build/CMakeFiles  81 82
[ 88%] Built target pygen_python_trx_34d24
make -f apps/CMakeFiles/pygen_apps.dir/build.make apps/CMakeFiles/pygen_apps.dir/depend
make[2]: Entering directory '/home/shock/gr-gsm/build'
cd /home/shock/gr-gsm/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/shock/gr-gsm /home/shock/gr-gsm/apps /home/shock/gr-gsm/build /home/shock/gr-gsm/build/apps /home/shock/gr-gsm/build/apps/CMakeFiles/pygen_apps.dir/DependInfo.cmake --color=
Dependee "/home/shock/gr-gsm/build/apps/CMakeFiles/pygen_apps.dir/DependInfo.cmake" is newer than depender "/home/shock/gr-gsm/build/apps/CMakeFiles/pygen_apps.dir/depend.internal".
Dependee "/home/shock/gr-gsm/build/apps/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/shock/gr-gsm/build/apps/CMakeFiles/pygen_apps.dir/depend.internal".
Scanning dependencies of target pygen_apps
make[2]: Leaving directory '/home/shock/gr-gsm/build'
make -f apps/CMakeFiles/pygen_apps.dir/build.make apps/CMakeFiles/pygen_apps.dir/build
make[2]: Entering directory '/home/shock/gr-gsm/build'
/usr/local/bin/cmake -E cmake_progress_report /home/shock/gr-gsm/build/CMakeFiles 67
[ 89%] Generating grgsm_livemon
cd /home/shock/gr-gsm/build/apps && /usr/local/bin/cmake -E env PYTHONPATH="/home/shock/gr-gsm/python:/home/shock/gr-gsm/python/misc_utils:/home/shock/gr-gsm/python/demapping:/home/shock/gr-gsm/python/receiver:/home/shock/gr-gsm/python/transmitter:/home/shock/gr-gsm/python/trx:/home/shock/gr-gsm/build/swig" GRC_BLOCKS_PATH=/home/shock/gr-gsm/grc /usr/local/bin/grcc -d /home/shock/gr-gsm/build/apps /home/shock/gr-gsm/apps/grgsm_livemon.grc
Segmentation fault
make[2]: *** [apps/CMakeFiles/pygen_apps.dir/build.make:82: apps/grgsm_livemon] Error 1
make[2]: Leaving directory '/home/shock/gr-gsm/build'
make[1]: *** [CMakeFiles/Makefile2:1173: apps/CMakeFiles/pygen_apps.dir/all] Error 2
make[1]: Leaving directory '/home/shock/gr-gsm/build'
make: *** [Makefile:127: all] Error 2
`

So I tried :

`
grcc -d /home/shock/gr-gsm/build/apps /home/shock/gr-gsm/apps/grgsm_livemon.grc
Block key "gsm_bcch_ccch_demapper" not found
Block key "gsm_clock_offset_control" not found
Block key "gsm_control_channels_decoder" not found
Block key "gsm_control_channels_decoder" not found
Block key "gsm_decryption" not found
Block key "gsm_input" not found
Block key "gsm_message_printer" not found
Block key "gsm_receiver" not found
Block key "gsm_sdcch8_demapper" not found
Validation failed:

Block - import_1 - Import(import):
	Param - Import(import):
		Import "from grgsm import arfcn" failed.
Error during file compilation.
Segmentation fault
`

And followed this issue : [https://github.com/ptrkrysik/gr-gsm/issues/399](https://github.com/ptrkrysik/gr-gsm/issues/399) but same result, I'm stuck on this bug.

**Comment by velichkov** [comment]
Hi @Sh0ckFR,

Please never edit your messages as github does not send emails with the edited text.

Please use markdown formatting when pasting logs, the build logs in your message are on one line which makes them hard to understand. 

> grcc path: /usr/local/bin/grcc

You still have the `gnuradio` version installed by `pybombs`, the one in `/usr/local/bin/`. Removing the `pybombs` does not remove all packages installed by it so I guess you need to remove them manually.

When did you installed `pybombs` and `gnuradio` with it, before or after you experience the segmentation fault build failure?

>  on a fresh Kali rolling version

Because this is a fresh installation my advice is to start again from scratch by formatting and re-installing the system and on the new one **do not** install `pybombs`.

> if I try to install the debian package directly, I have the same issue than : #426

Could you copy-paste few lines around line 212 from /usr/bin/grgsm_scanner

> grcc -d /home/shock/gr-gsm/build/apps /home/shock/gr-gsm/apps/grgsm_livemon.grc
> Param - Import(import):
Import "from grgsm import arfcn" failed.To compile it manually like 

To compile it manually like this you first need to export a lot of environment variables. The easiest way to get them is by running  `make VERBOSE=1`, it's going to display the full command together with all variables. You need to copy-paste the environment variables and export  them in your shell.

> [ 89%] Generating grgsm_livemon Segmentation fault 

I'll try to reproduce this crash but it's going to take me some time.

**Comment by velichkov** [comment]
Hi @AlexeiScherbakov,

Have you been able to resolve the `Segmentation fault` issue you've reported in https://github.com/ptrkrysik/gr-gsm/issues/399#issuecomment-399944362 and if yes how?

I'm still not able to reproduce the crash in a Docker container 
```
docker build -f tests/dockerfiles/Kali.docker -t gr-gsm-kali-rolling .
```
which only proves that if you start from a fresh clean Kali installation and follow the commands in the `tests/dockerfiles/Kali.docker` you could successfully install `gr-gsm`

**Comment by Sh0ckFR** [comment]
Well I finally fixed the issue like that :

apt-get install pybombs -> to reinstall pybombs
pybombs remove gnuradio
apt-get install --reinstall gnuradio
cd .. && rm -rf build/ && mkdir build && cd build
cmake ..
make
make install
export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/grgsm:$PYTHONPATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
grgsm_livemon

Sorry about the markdown, my keyboard is a bit broken, best way is to never use pybombs.

**Comment by velichkov** [comment]
> Well I finally fixed the issue like that :

That's great :smile:  Now please close this issue.

> export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

I'm not quite sure whether you need exporting PYTHONPATH or not,  but instead of exporting LD_LIBRARY_PATH you could run `ldconfig` after `make install`

**Comment by Sh0ckFR** [comment]
Thank you for your help anyway, have a good day.

**Comment by justicexxx** [comment]
97 / 5000
Çeviri sonuçları
I have a problem too, although I did everything right, I cannot find the frequencies. Please help 

![Screenshot 2021-05-04 21:34:30](https://user-images.githubusercontent.com/83667696/117054468-cde8a000-ad22-11eb-8728-982014ff80e2.png)
