### ISSUE TITLE
description  about  how to decode gsm signal

### ISSUE THREAD

**Issue by Mitchell1314** [ptrkrysik/gr-gsm#429]
Hi sir,
   I have red your code recently and want to have a good knowledge about procedure of decoding GSM signal. Unfortunately, I found it difficult without any basis of GSM demodulation and decoding. So I wanna ask you if you have any detailed description abou your code. Maybe do you have any book or resources to recommend?

**Comment by ptrkrysik** [comment]
@Mitchell1314 the project mailing list is much more appropriate for such topics. Could you ask there?
Some pointers about demodulation are here:
https://groups.google.com/forum/#!searchin/gr-gsm/viterbi|sort:date/gr-gsm/W3Ko0kX1rhk/mw6_UJJTAQAJ
https://groups.google.com/forum/#!searchin/gr-gsm/viterbi|sort:date/gr-gsm/VNy234f3jZM/by1azz8WAgAJ

For decoding it's mostly 3gpp 05.03 specification and implementation in libosmocoding.
