### ISSUE TITLE
how to Decode A5/0. some one can write down the command to do it?

### ISSUE THREAD

**Issue by phamduythai92mta** [ptrkrysik/gr-gsm#438]

**Comment by velichkov** [comment]
Hi @phamduythai92mta,

A5/0 is no encryption at all, so read the [Decoding-How-To](https://github.com/ptrkrysik/gr-gsm/wiki/Usage:-Decoding-How-To) and do not specify `-e` and `-k` options (`--a5` and `--kc` as well)

P.S.
It's better to post your questions to the [Mailing List](https://github.com/ptrkrysik/gr-gsm#mailing-list)

**Comment by phamduythai92mta** [comment]
thank you so much for answer! i got it!
