### ISSUE TITLE
grgsm_capture arguments 

### ISSUE THREAD

**Issue by prkrmx** [ptrkrysik/gr-gsm#441]
Hello
I have two receivers in my system name=RX_1 and name=RX_2
I found that I cant launch grgsm_capture for the selected receiver
Every time the RX_1 receiver starts working
grgsm_capture -a 89 --args="name=RX_2" -T 10

GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.12.0.0-59-g523994c7
gr-osmosdr v0.1.4-99-gc98be5dd (0.1.5git) gnuradio 3.7.12.0
ubuntu 16

thanks

**Comment by velichkov** [comment]
> product: B205mini

Try adding `uhd,` before the `name` - e.g. `grgsm_capture -a 89 --args="uhd,name=RX_2" -T 10`
See also https://osmocom.org/projects/gr-osmosdr/wiki#UHD-Source-Sink

**Comment by prkrmx** [comment]
Thanks for the quick response  @velichkov 
It works as expected

**Comment by velichkov** [comment]
> Thanks for the quick response

You are welcome. 

> It works as expected

Could you please close the issue?
