### ISSUE TITLE
LTE-Cell-Scanner problem

### ISSUE THREAD

**Issue by stathis94s** [ptrkrysik/gr-gsm#449]
CellSearch: error while loading shared libraries: libitpp.so.8: cannot open shared object file: No such file or directory

**Comment by velichkov** [comment]
Hi @stathis94s,

Better report this problem in the [LTE-Cell-Scanner](https://github.com/Evrytania/LTE-Cell-Scanner/issues) project. Also try running `sudo ldconfig`

**Comment by stathis94s** [comment]
Thanks for answering @velichkov i tried out your suggestion but nothing changed,so i'm gonna make an issue there.
