### ISSUE TITLE
grgsm_scanner result in sqlite

### ISSUE THREAD

**Issue by jbdu94** [ptrkrysik/gr-gsm#466]
Hi

I am trying to get the results of grgsm_scanner into a sqlite database, in order to only the strongest tower per mobile phone provider (same MCC, same MNC but keep only the strongest power)

However, I fail to modify the code.
I declared in the def do_scan():

`con = sqlite3.connect("toto.db") # database file input
	    cur = con.cursor()
	    cur.executescript("""
		DROP TABLE IF EXISTS t;
		CREATE TABLE t (ARFCN TEXT, FREQ TEXT, CID TEXT, LAC TEXT, MCC TEXT, MNC TEXT, SIGNAL TEXT);
		""")# checks to see if table exists and makes a fresh table.`

On the part:

` for i in range(0, len(chans)):
                        cell_arfcn_list = scanner.gsm_extract_system_info.get_cell_arfcns(chans[i])
                        neighbour_list = scanner.gsm_extract_system_info.get_neighbours(chans[i])

                    info = channel_info(grgsm.arfcn.downlink2arfcn(found_freqs[i]), found_freqs[i],
                                        cell_ids[i], lacs[i], mccs[i], mncs[i], ccch_confs[i], powers[i],
                                        neighbour_list, cell_arfcn_list)`

I added 

`                   cur.execute("INSERT INTO t (ARFCN) VALUES (?)", found_freqs[i])
                    cur.execute("INSERT INTO t (FREQ) VALUES (?)", found_freqs[i])
                    cur.execute("INSERT INTO t (CID) VALUES (?)", cell_ids[i])
                    cur.execute("INSERT INTO t (LAC) VALUES (?)", lacs[i])
                    cur.execute("INSERT INTO t (MCC) VALUES (?)", mccs[i])
                    cur.execute("INSERT INTO t (MNC) VALUES (?)", mncs[i])
                    cur.execute("INSERT INTO t (SIGNAL) VALUES (?)", powers[i])`

but the database is empty (created but empty).
Any idea?
I think this could be also interesting for other people too, so I propose to share my small modification with your repo, if it's OK (once I will fix my code, of course). Would you be OK?
Or maybe you plan to add SQLITE option too ?

**Comment by velichkov** [comment]
Hi @jbdu94,

Would it be possible for you to edit your message and use [markdown](https://guides.github.com/features/mastering-markdown/) to format the code as right now it's mostly unreadable.

Also it is a lot easier to discuss code changes if you fork the repository and commit and push your changes to your fork. This way anybody could fetch and test your changes and also review and comment directly in the github.

You probably need to [commit](https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.commit) the transaction and [close](
https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.close) the connection. Also you probably want to have a single raw per found ARFCN so you'll need to use a single `INSERT INTO` statement, something like:
```python
cur.execute("INSERT INTO t (ARFCN, FREQ, CID, LAC, MCC, MNC, SIGNAL)"
        " VALUES (?, ?, ?, ?, ?, ?, ?)",
        grgsm.arfcn.downlink2arfcn(found_freqs[i]),
        found_freqs[i],
        cell_ids[i],
        lacs[i],
        mccs[i],
        mncs[i],
        powers[i]))
```
