### ISSUE TITLE
[Failed] $ sudo ./pybombs install gr-gsm

### ISSUE THREAD

**Issue by eidlyn** [ptrkrysik/gr-gsm#47]
I was installing the file, and the build failed. These are the last few lines that were outputted to the screen:

[100%] Building CXX object gr-trellis/lib/CMakeFiles/gnuradio-trellis.dir/siso_f_impl.cc.o
[100%] Building CXX object gr-trellis/lib/CMakeFiles/gnuradio-trellis.dir/siso_combined_f_impl.cc.o
Linking CXX shared library libgnuradio-trellis-3.7.8git.so
[100%] Built target gnuradio-trellis
Scanning dependencies of target _trellis_swig
[100%] Building CXX object gr-trellis/swig/CMakeFiles/_trellis_swig.dir/trellis_swigPYTHON_wrap.cxx.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
make[2]: *** [gr-digital/swig/CMakeFiles/_digital_swig.dir/digital_swigPYTHON_wrap.cxx.o] Error 4
make[1]: *** [gr-digital/swig/CMakeFiles/_digital_swig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared module _trellis_swig.so
[100%] Built target _trellis_swig
make: *** [all] Error 2
Build failed. See output above for error messages.

The machine is the Offensive Security image of Kali Linux 1.1.0, where all the packages were up to date as of about 11 pm Sunday May the 3rd 2015. I allocated 8 gb of memory and 2 cpu cores, because the build failed earlier with the default 2gb, saying the virtual machine had run out of memory.

I saved all my inputs and outputs from this session if they are necessary. I can also post the output of any logs if needed.

**Comment by ptrkrysik** [comment]
Hi, somehow I haven't replied yet to this issue. This is some GNU Radio error. Maybe the version at that particular moment didn't compile and now it works? Can you check it?
