### ISSUE TITLE
Sampling rate  not support  USRP X310  

### ISSUE THREAD

**Issue by czl1989** [ptrkrysik/gr-gsm#470]
how to support USRP X310？  Thanks

**Comment by velichkov** [comment]
Hi @czl1989,

> how to support USRP X310？

All USRP devices are supported. We are using `gr-osmosdr` project internally and all devices supported by `gr-osmosdr` are supported by `gr-gsm` as well.

> Sampling rate not support USRP X310

Could you describe exactly what is not supported by your device?

**Comment by czl1989** [comment]
Project set rx sample rate is 270.833k*4. USRP1 clock is 52M can support 270.833k*4. USRP x310 clock is 200M can not support 270.833k*4. I change the sample rate for 390.625k*4, but the tx tag is wrong.

**Comment by velichkov** [comment]
Hi @czl1989,

> I change the sample rate for 390.625k4, but the tx tag is wrong.

Is the problem in `grgsm_trx` as the other gr-gsm applications do not use tx_time tags?
Could you describe in some more details what you are trying to do?

**Comment by ptrkrysik** [comment]
For grgsm_trx - devices other than USRPs B2x0 are not supported yet. I'm working on it (as part of effort to add frequency hopping to grgsm_trx) but it's not done yet.
