### ISSUE TITLE
Unable to decode DCS or PCS

### ISSUE THREAD

**Issue by akibsayyed** [ptrkrysik/gr-gsm#52]
Dear Piotr 

I am testing your implementation on DCS, PCS it used to work before but latest build is not working

**Comment by ptrkrysik** [comment]
@akibsayyed this is strange as DCS and PCS are exactly like GSM900 - just on different carrier frequency. Are you able to point the commit number or at least quite precise date when it worked?

**Comment by akibsayyed** [comment]
I tried it approx in august 2014 it was working. I will send you cfile for
same today.

On Tue, May 19, 2015 at 11:53 AM, Piotr Krysik <notifications@github.com>
wrote:

> @akibsayyed <https://github.com/akibsayyed> this is strange as DCS and
> PCS are exactly like GSM900 - just on different carrier frequency. Are you
> able to point the commit number or at least quite precise date when it
> worked?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ptrkrysik/gr-gsm/issues/52#issuecomment-103357264>.
>



-- 
Akib Sayyed
Matrix-Shell
akibsayyed@gmail.com
akibsayyed@matrixshell.com
Mob:- +91-966-514-2243

**Comment by ptrkrysik** [comment]
This is problem with DC offset of your hardware.  For example it can be tackled by inserting DC blocker block between signal source and the "GSM input adaptor".

**Comment by ptrkrysik** [comment]
There might be something wrong with frequency correction. In the file that I downloaded from you (the link is in #53) I found out that I get much better results when I put central frequency 931MHz and not 1931MHz that it was really recorded on. I will look into this issue in the free time.

**Comment by ptrkrysik** [comment]
Hi @akibsayyed,

You were right - there was an error. I think I corrected it in this commit:
https://github.com/ptrkrysik/gr-gsm/commit/18f769026cdda9e1bbacd772c5afb277cf56da00

**Comment by ptrkrysik** [comment]
I'm closing it for now. If you still have problem I will reopen it.
