### ISSUE TITLE
grgsm_decode for burst sylvain / burst_ind branch in OsmocomBB

### ISSUE THREAD

**Issue by Victor6112** [ptrkrysik/gr-gsm#522]
Question: There is a sylvain / burst_ind branch in OsmocomBB. When starting Motorola we get bursts - files bursts_20200317_0118_874_2017270_61.dat

Can we view them through Wereshark as well as .cfile files?
If we can, then how? I could not find it on the network. In grgsm_decode -h there is -b switch for burst but I couldn’t start viewing traffic.

**Comment by velichkov** [comment]
> Question: There is a sylvain / burst_ind branch in OsmocomBB. When starting Motorola we get bursts - files bursts_20200317_0118_874_2017270_61.dat
> 
> Can we view them through Wereshark as well as .cfile files?

> If we can, then how? I could not find it on the network.

I don't know. Better ask this in the [osmocom's mailing list](https://lists.osmocom.org/mailman/listinfo).

> In grgsm_decode -h there is -b switch for burst but I couldn’t start viewing traffic.

A previous version of `grgsm_capture` supported capturing of burst files but this feature was removed in 81ba56f59dcefb2d39d023c68d3a077b4a321520, I doubt that the used format was the same as the one in OsmocomBB. See also https://groups.google.com/d/msg/gr-gsm/EjOfB6L21GM/8Yqrf6AhAwAJ

P.S.
You can post questions like this to our [mailing list](https://github.com/ptrkrysik/gr-gsm/#mailing-list)
