### ISSUE TITLE
Mobile broadband card is not a supported device ?

### ISSUE THREAD

**Issue by e2002e** [ptrkrysik/gr-gsm#527]
Hello, I have a laptop with a card named:
usb-Foxconn_Dell_Wireless_5630__EVDO-HSPA__Mobile_Broadband_Mini-Card
Is had these capabilities:
+GCAP: +CIS707-A, CIS-856, CIS-856-A, CIS707,+MS, +ES, +DS, +FCL
can be used with gr-gsm ?
The error I get from grgsm_livemon is:
RuntimeError: Unable to find any supported SDR devices

**Comment by velichkov** [comment]
Hi @e2002e,

No. You need an SDR device like [RTL SDR](https://www.rtl-sdr.com/about-rtl-sdr/), [Ettus USRP](https://www.ettus.com/products/), [LimeSDR](https://limemicro.com/products/boards/), ...

**Comment by e2002e** [comment]
Thank you. I can't wait to play with radio frequency !
