### ISSUE TITLE
GNURADIO Building Error- [ 16%] Linking CXX shared module _pmt_swig.so

### ISSUE THREAD

**Issue by cyb3rzest** [ptrkrysik/gr-gsm#555]
Hi, I tried to install gnuradio using pybombs and source-code, but getting this error.
Anyone can help me back please.

make[1]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  6%] Built target volk_obj
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  6%] Built target volk
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  7%] Built target volk_test_all
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target volk-config-info
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target volk_profile
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target pygen_volk_python_volk_modtool_be0ec
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target pygen_volk_python_volk_modtool_b1063
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target doxygen_target
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[  8%] Built target gnuradio-pmt
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 13%] Built target gnuradio-runtime
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 13%] Built target pmt_unv
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 13%] Built target runtime_qa_buffer.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 14%] Built target runtime_qa_circular_file.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 14%] Built target runtime_qa_io_signature.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_sincos.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_math.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target runtime_qa_vmcircbuf.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_fxpt.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target runtime_qa_logger.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_fxpt_nco.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_fxpt_vco.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target math_qa_fast_atan2f.cc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 15%] Built target pmt_prims
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 16%] Built target gnuradio-config-info
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 16%] Built target _pmt_swig_doc_tag
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 16%] Built target pmt_swig_swig_doc
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
[ 16%] Built target pmt_swig_swig_compilation
make[2]: Entering directory '/usr/local/src/gnuradio/build'
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
make[2]: Entering directory '/usr/local/src/gnuradio/build'
[ 16%] Linking CXX shared module _pmt_swig.so
/usr/bin/ld: /usr/local/lib/libpython3.8.a(pythonrun.o): warning: relocation against `_Py_UnhandledKeyboardInterrupt' in read-only section `.text.unlikely'
/usr/bin/ld: /usr/local/lib/libpython3.8.a(abstract.o): relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [gnuradio-runtime/swig/CMakeFiles/pmt_swig.dir/build.make:98: gnuradio-runtime/swig/_pmt_swig.so] Error 1
make[2]: Leaving directory '/usr/local/src/gnuradio/build'
make[1]: *** [CMakeFiles/Makefile2:4765: gnuradio-runtime/swig/CMakeFiles/pmt_swig.dir/all] Error 2
make[1]: Leaving directory '/usr/local/src/gnuradio/build'
make: *** [Makefile:141: all] Error 2
[CMakeOutput.log](https://github.com/ptrkrysik/gr-gsm/files/5128650/CMakeOutput.log)
[CMakeError.log](https://github.com/ptrkrysik/gr-gsm/files/5128651/CMakeError.log)

**Comment by aarogita** [comment]
> Hi, I tried to install gnuradio using pybombs and source-code, but getting this error.
> Anyone can help me back please.
> 
> make[1]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 6%] Built target volk_obj
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 6%] Built target volk
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 7%] Built target volk_test_all
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target volk-config-info
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target volk_profile
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target pygen_volk_python_volk_modtool_be0ec
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target pygen_volk_python_volk_modtool_b1063
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target doxygen_target
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 8%] Built target gnuradio-pmt
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 13%] Built target gnuradio-runtime
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 13%] Built target pmt_unv
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 13%] Built target runtime_qa_buffer.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 14%] Built target runtime_qa_circular_file.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 14%] Built target runtime_qa_io_signature.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_sincos.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_math.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target runtime_qa_vmcircbuf.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_fxpt.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target runtime_qa_logger.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_fxpt_nco.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_fxpt_vco.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target math_qa_fast_atan2f.cc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 15%] Built target pmt_prims
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 16%] Built target gnuradio-config-info
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 16%] Built target _pmt_swig_doc_tag
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 16%] Built target pmt_swig_swig_doc
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> [ 16%] Built target pmt_swig_swig_compilation
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> make[2]: Entering directory '/usr/local/src/gnuradio/build'
> [ 16%] Linking CXX shared module _pmt_swig.so
> /usr/bin/ld: /usr/local/lib/libpython3.8.a(pythonrun.o): warning: relocation against `_Py_UnhandledKeyboardInterrupt' in read-only section `.text.unlikely'
> /usr/bin/ld: /usr/local/lib/libpython3.8.a(abstract.o): relocation R_X86_64_PC32 against symbol `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [gnuradio-runtime/swig/CMakeFiles/pmt_swig.dir/build.make:98: gnuradio-runtime/swig/_pmt_swig.so] Error 1
> make[2]: Leaving directory '/usr/local/src/gnuradio/build'
> make[1]: *** [CMakeFiles/Makefile2:4765: gnuradio-runtime/swig/CMakeFiles/pmt_swig.dir/all] Error 2
> make[1]: Leaving directory '/usr/local/src/gnuradio/build'
> make: *** [Makefile:141: all] Error 2
> [CMakeOutput.log](https://github.com/ptrkrysik/gr-gsm/files/5128650/CMakeOutput.log)
> [CMakeError.log](https://github.com/ptrkrysik/gr-gsm/files/5128651/CMakeError.log)
