### ISSUE TITLE
GR-GSM with 3G UMTS

### ISSUE THREAD

**Issue by Al3x4n** [ptrkrysik/gr-gsm#571]
Could gr-gsm scan NodeB 3G UMTS?
Or someone tell me similar project can do scan NodeB 3G Cell?

**Comment by velichkov** [comment]
> Could gr-gsm scan NodeB 3G UMTS?

No.

> Or someone tell me similar project can do scan NodeB 3G Cell?

I'm not aware of such projects

**Comment by Al3x4n** [comment]
Thanks for quick reply :)
