### ISSUE TITLE
[ERROR] SoapySDR::loadModule(/usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so)   dlopen() failed: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so: undefined symbol: _ZN5boost6chrono12steady_clock3nowEv [ERROR] avahi_service_browser_new() failed: Bad state

### ISSUE THREAD

**Issue by fuckwbored** [ptrkrysik/gr-gsm#575]
[ERROR] SoapySDR::loadModule(/usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so)
  dlopen() failed: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so: undefined symbol: _ZN5boost6chrono12steady_clock3nowEv
[ERROR] avahi_service_browser_new() failed: Bad state

**Comment by velichkov** [comment]
> [ERROR] SoapySDR::loadModule(/usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so)
> dlopen() failed: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librfspaceSupport.so: undefined symbol: _ZN5boost6chrono12steady_clock3nowEv

Report this to Kali/Debian package maintainers. As you are using an RTL dongle you can safely ignore this error.

> [ERROR] avahi_service_browser_new() failed: Bad state

You can ignore this as well.

As you are using an RTL dongle you can suppress these errors by executing `grgsm_scanner --debug --args=rtl`

**Comment by fuckwbored** [comment]
thx! but i don't have any result in wireshark

**Comment by fuckwbored** [comment]
![image](https://user-images.githubusercontent.com/68074768/117988874-7b236f80-b344-11eb-84bc-7fa94ac4ba8b.png)
and i dont have anu result in terminal when im ussing grgsm_livemon

**Comment by velichkov** [comment]
> but i don't have any result in wireshark

`grgsm_scanner` does not send anything to Wireshark and that is by design. 

> and i dont have anu result in terminal when im ussing grgsm_livemon

The most probable reason is that there is no GSM cell on the selected frequency. How did you choose 946.6MHz?

**Comment by fuckwbored** [comment]
I did not choose anything, it stood by default. What to do? I meant that when opening wireShark there are no GSM protocols

**Comment by velichkov** [comment]
> What to do? I meant that when opening wireShark there are no GSM protocols

First you  need to find a frequency of a nearby GSM cell using `grgsm_scanner`, your smartpone or one of the many web sites and then you need to start `grgsm_livemon` on this frequency.

**Comment by fuckwbored** [comment]
thank you!!!!!!!
