### ISSUE TITLE
error when run *grgsm

### ISSUE THREAD

**Issue by Europe-Connection** [ptrkrysik/gr-gsm#576]
Hello, I am on Ubuntu 20.04 LTS version. I managed to install gr-gsm correctly. However to use functions like grgsm_scanner or grgsm_livemon I must type `PYTHONPATH = / usr / local / lib / python3 / dist-packages /: $ PYTHONPATH`.

 Is there a solution to not having to enter this command line?
Thanks for your help

**Comment by velichkov** [comment]
Hi @Europe-Connection,

You can modify `PYTHONPATH` in `~/.profile`

```
export PYTHONPATH=/usr/local/lib/python3/dist-packages/:$PYTHONPATH
```

**Comment by Europe-Connection** [comment]
It's ok thank you very much
