### ISSUE TITLE
Getting Frame Numbers in CX 

### ISSUE THREAD

**Issue by akibsayyed** [ptrkrysik/gr-gsm#62]
I havent tried to decode multiple Channels with single GSM block but would like to know if we are getting frame number on CX wrt hopping channel.

Also what about timeslot details. are we able to get timeslot details on CX wrt supplied channel

**Comment by ptrkrysik** [comment]
Bursts coming through CX port have proper frame number and timeslot
number set in their GSMTAP headers. You can connect CX output to PDU
socket sink and observe this in Wireshark or with burst printer.
