### ISSUE TITLE
Possible to settle the RTL-SDR dongle as a BSC or a BTS ?

### ISSUE THREAD

**Issue by aymeric75** [ptrkrysik/gr-gsm#75]
I'm trying to recreate a mini GSM network using Osmocom Suite, the problem is that it require a BTS (see requirements part: http://openbsc.osmocom.org/trac/wiki/OpenBSC#WhatisOpenBSC ), but i can't find one yet, so i'm wondering if i can use my RTL-SDR as a BTS....

Cheers

Aymeric

**Comment by NinjaComics** [comment]
@aymeric75 RTL-SDR dongle is receive only. So technically it's not possible to setup a BSC with RTL-SDR.

**Comment by aymeric75** [comment]
@NinjaComics Thank you, do you know a cheap way to make a GSM network (between two phones directly or a phone and a BTS) ? 

From what i've read for now, one need a physical BTS but maybe there is a "simplier" way...

**Comment by NinjaComics** [comment]
There is Calypso BTS (to make the calypso based baseband work as frontend for your BTS), if you prefer cheap GSM network. But that setup requires Calypso based phones, which are quite extinct to buy these days.

**Comment by aymeric75** [comment]
Thank you, do you think this model is okay ?

http://www.ebay.fr/itm/British-Telecom-Calypso-120-Single-Line-Cordless-Phone-/291496032171?pt=LH_DefaultDomain_3&hash=item43de8477ab

**Comment by NinjaComics** [comment]
@aymeric75 No. Please check this [osmocomBB wiki page](http://bb.osmocom.org/trac/wiki/Hardware/Phones) for the list of phones with Calypso baseband.

**Comment by NinjaComics** [comment]
@ptrkrysik this issue can be closed
