### ISSUE TITLE
How to save datas in a .bin files ?

### ISSUE THREAD

**Issue by aymeric75** [ptrkrysik/gr-gsm#78]
HI everyone,

I would like to know which command do i have to use to save a live gsm session (i use the command "airprobe_rtlsdr.py" to see the frequencies graph) ?

Thanks

**Comment by ptrkrysik** [comment]
Hi @aymeric75 ,

As we now have gr-gsm google group I wan't such questions (that are not related to a specific issue with gr-gsm or new functionality that should be implemented) to be asked there.
If you ask the question using the group - I will answer it.

The description how to join the group is here:
https://github.com/ptrkrysik/gr-gsm#mailing-list

**Comment by ptrkrysik** [comment]
The answer is on the google group:
https://groups.google.com/forum/#!topic/gr-gsm/1C7LQCOgLEY
