### ISSUE TITLE
Airprobe-like bursts

### ISSUE THREAD

**Issue by bluelightvision** [ptrkrysik/gr-gsm#80]
Hi, is there a way to get the bursts of a certain timeslot as can be done using airprobe (C1 and C0 bursts)?
ex:
C1 1015026 1567500: 100000010001110101010000000010100000000111111101010000001010000100010111010100000000101000010000010101010100000010
P1 1015026 1567500: 100000010001110101010000000010100000000111111101010000001010000100010111010100000000101000010000010101010100000010
S1 1015026 1567500: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
C0 1015027 1567533: 101010111111111101000000101010101111111111110100000000100010111111111111010101000000001010101011011101010000001000
P0 1015027 1567533: 101010111111111101000000101010101111111111110100000000100010111111111111010101000000001010101011011101010000001000
S0 1015027 1567533: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
C0 1015028 1567566: 000000011111010101010000100000010001010111010101000010100001010001111101010001000010000000000101110101010100000010
P0 1015028 1567566: 000000011111010101010000100000010001010111010101000010100001010001111101010001000010000000000101110101010100000010
S0 1015028 1567566: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
C0 1015029 1567599: 000100001010101010111101110101010000000010101110111111010100010000001010101011011101010001000010001011101111010101
P0 1015029 1567599: 000100001010101010111101110101010000000010101110111111010100010000001010101011011101010001000010001011101111010101
S0 1015029 1567599: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
1015029 5: 03 03 01 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b 2b

**Comment by ptrkrysik** [comment]
Hi @bluelightvision,

I want keep github issues more focussed on fixing bugs and implementing new features.

The place for more general discussion is now project's mailing list:
https://github.com/ptrkrysik/gr-gsm/#mailing-list

If you ask the question there I will answer it.
