### ISSUE TITLE
Burst source thread join 

### ISSUE THREAD

**Issue by romankh** [ptrkrysik/gr-gsm#89]
There is a bug with the join() of d_thread. 
Currently the burst source throws an exception, and therefore the flow graph stops. 
The cause is imho that 
```
        d_thread->interrupt();
        d_thread->join();
``` 
are currently executed in the child thread, and d_thread also references the child thread. 

I moved the statements back to the stop function, however then again the flow graph didn't terminate.

Finally I found the intended method to archive a proper termination in this post https://lists.gnu.org/archive/html/discuss-gnuradio/2015-05/msg00287.html

So I added `post(pmt::mp("system"), pmt::cons(pmt::mp("done"), pmt::from_long(1)));` to the end of the run() function. 

Pull request follows.

**Comment by ptrkrysik** [comment]
I have messed something with multithreading when I tried to make this
block exit when all input bursts are processed. Merging your change.

**Comment by romankh** [comment]
Closing this issue, should be fixed with the above merge.
