### ISSUE TITLE
Build problem on 14.10

### ISSUE THREAD

**Issue by dmaynor** [ptrkrysik/gr-gsm#9]
Scanning dependencies of target gnuradio-gsm
[  3%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/receiver/receiver_impl.cc.o
[  6%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/receiver/receiver_config.cc.o
[  9%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/receiver/viterbi_detector.cc.o
[ 12%] Building C object lib/CMakeFiles/gnuradio-gsm.dir/receiver/sch.c.o
[ 15%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/bursts_printer_impl.cc.o
[ 18%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/extract_system_info_impl.cc.o
[ 21%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/demapping/universal_ctrl_chans_demapper_impl.cc.o
[ 25%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/demapping/get_bcch_or_ccch_bursts_impl.cc.o
[ 28%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/decoding/control_channels_decoder_impl.cc.o
/home/dmaynor/code/gr-gsm/lib/decoding/control_channels_decoder_impl.cc: In member function ‘void gr::gsm::control_channels_decoder_impl::decode(pmt::pmt_t)’:
/home/dmaynor/code/gr-gsm/lib/decoding/control_channels_decoder_impl.cc:134:41: warning: iteration 27u invokes undefined behavior [-Waggressive-loop-optimizations]
                 outmsg[pos++] = c & 0xff;
                                         ^
/home/dmaynor/code/gr-gsm/lib/decoding/control_channels_decoder_impl.cc:130:12: note: containing loop
            for(i = 0; i < sbuf_len; i += 8) {
            ^
[ 31%] Building C object lib/CMakeFiles/gnuradio-gsm.dir/decoding/cch.c.o
[ 34%] Building C object lib/CMakeFiles/gnuradio-gsm.dir/decoding/fire_crc.c.o
[ 37%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/controlled_rotator_cc_impl.cc.o
[ 40%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/controlled_const_source_f_impl.cc.o
[ 43%] Building CXX object lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/message_printer_impl.cc.o
/home/dmaynor/code/gr-gsm/lib/misc_utils/message_printer_impl.cc: In member function ‘void gr::gsm::message_printer_impl::message_print(pmt::pmt_t)’:
/home/dmaynor/code/gr-gsm/lib/misc_utils/message_printer_impl.cc:44:52: error: ‘printf’ was not declared in this scope
             printf(" %02x", message_plus_header[ii]);
                                                    ^
lib/CMakeFiles/gnuradio-gsm.dir/build.make:353: recipe for target 'lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/message_printer_impl.cc.o' failed
make[2]: **\* [lib/CMakeFiles/gnuradio-gsm.dir/misc_utils/message_printer_impl.cc.o] Error 1
CMakeFiles/Makefile2:205: recipe for target 'lib/CMakeFiles/gnuradio-gsm.dir/all' failed
make[1]: **\* [lib/CMakeFiles/gnuradio-gsm.dir/all] Error 2
Makefile:123: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Spanky1503** [comment]
im having a build problem also here is the error im getting 

In file included from /usr/local/gr-gsm/lib/misc_utils/controlled_rotator_cc_impl.h:27:0,
                 from /usr/local/gr-gsm/lib/misc_utils/controlled_rotator_cc_impl.cc:28:
/usr/include/gnuradio/blocks/rotator.h: In member function ‘void gr::blocks::rotator::rotateN(gr_complex*, const gr_complex*, int)’:
/usr/include/gnuradio/blocks/rotator.h:62:75: error: ‘volk_32fc_s32fc_x2_rotator_32fc’ was not declared in this scope
         volk_32fc_s32fc_x2_rotator_32fc(out, in, d_phase_incr, &d_phase, n);
                                                                           ^
make[2]: *** [lib/CMakeFiles/grgsm.dir/misc_utils/controlled_rotator_cc_impl.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/grgsm.dir/all] Error 2
make: *** [all] Error 2
